/* autogenerated decompilation stub */
/* source asm: auto_03_80039FF8_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_80039FF8 (size: 0x2CC)
// fn_8003A2C4 (size: 0x4FC)
// fn_8003A7C0 (size: 0x158)
// fn_8003A918 (size: 0x90)
// fn_8003A9A8 (size: 0x74)
// fn_8003AA1C (size: 0x28)
// fn_8003AA44 (size: 0x24)
// fn_8003AA68 (size: 0x40)
