/* autogenerated decompilation stub */
/* source asm: auto_03_801CB834_text.s */

/* FUNCTIONS TO DECOMPILE */
// create__7JKRAramFUlUllll (size: 0x90)
// __ct__7JKRAramFUlUll (size: 0x12C)
// __dt__7JKRAramFv (size: 0x90)
// run__7JKRAramFv (size: 0x68)
// mainRamToAram__7JKRAramFPUcUlUl15JKRExpandSwitchUlP7JKRHeapi (size: 0x268)
// mainRamToAram__7JKRAramFPUcP12JKRAramBlockUl15JKRExpandSwitchUlP7JKRHeapi (size: 0xF0)
// aramToMainRam__7JKRAramFUlPUcUl15JKRExpandSwitchUlP7JKRHeapiPUl (size: 0x2F8)
// aramToMainRam__7JKRAramFP12JKRAramBlockPUcUlUl15JKRExpandSwitchUlP7JKRHeapiPUl (size: 0xB8)
