/* autogenerated decompilation stub */
/* source asm: auto_03_8003E70C_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_8003E70C (size: 0x6C)
// fn_8003E778 (size: 0xCC)
// fn_8003E844 (size: 0x29C)
// fn_8003EAE0 (size: 0x28)
// fn_8003EB08 (size: 0x2C)
// fn_8003EB34 (size: 0x254)
// fn_8003ED88 (size: 0x28)
// fn_8003EDB0 (size: 0x2A4)
// fn_8003F054 (size: 0x28)
// fn_8003F07C (size: 0x2C)
// fn_8003F0A8 (size: 0x6C)
// fn_8003F114 (size: 0x6C)
// fn_8003F180 (size: 0x14)
// fn_8003F194 (size: 0x14)
// fn_8003F1A8 (size: 0x10)
// fn_8003F1B8 (size: 0xC)
