/* autogenerated decompilation stub */
/* source asm: auto_03_80014278_text.s */
#include "auto_03_80014278_text.h"
/* FUNCTIONS TO DECOMPILE */
void fn_80014278(Unk_80014278* arg0){
    arg0->unk1C = 0;
    arg0->unk20 = 0;
    arg0->unk24 = 0;
    arg0->unk28 = 0;
    arg0->unk2C = 0;
    arg0->unk30 = 0;
    arg0->unk34 = 0;
    arg0->unk38 = 0;

    arg0->unk0  = 0;
    arg0->unk2  = 0;
    arg0->unk3C = 0;
    arg0->unk3D = 0;

    arg0->unkC  = 0;
    arg0->unk10 = 0;
    arg0->unk14 = 0;
    arg0->unk8  = 0;
}
// fn_800142C0 (size: 0x5C)
void fn_8001431C(Unk_8001431C* arg0){
    arg0->unk6 = 2;
    arg0->unk8 = 0;
    arg0->unkC = 0;
}


void fn_80014334(void) {}

void fn_80014338(void) {}

void fn_8001433C(void) {}

void fn_80014340(void) {}

void fn_80014344(void) {}

void fn_80014348(void) {}

void fn_8001434C(void) {}

void fn_80014350(void) {}

void fn_80014354(void) {}

void fn_80014358(void) {}

void fn_8001435C(void) {}

void fn_80014360(void) {}

// fn_80014364 (size: 0x164)
void fn_800144C8(s32 arg0, s32 arg1){

    s32 var_r31 = arg1;
    s32 var_r30 = arg0;

    GXSetNumChans(1);

    if (lbl_804A0D2D != 0) {
        var_r30 = 0;
    }

    {
        s32 light = lbl_80498BC4;
        s32 attn  = lbl_80498BC0;

        GXSetChanCtrl(0, var_r30, var_r31, var_r31, light, 2, attn);
    }

    {
        s32 light = lbl_80498BC4;
        s32 attn  = lbl_80498BC0;

        GXSetChanCtrl(2, 0, var_r31, var_r31, light, 2, attn);
    }
}


void fn_80014554(GXTexObj* arg0, void* arg1){
    UnkTexInitArg_80014554* p = (UnkTexInitArg_80014554*)arg1;

    GXInitTexObj(arg0, p->image, p->w, p->h, p->fmt, 0, 0, 0);

    GXInitTexObjLOD(arg0, 1, 1, 0, 0, 0, lbl_804A25E0, lbl_804A25E0, lbl_804A25E0);
}


void fn_800145C8(void) {
    lbl_804A0D24 = 0;
    lbl_804A0D28 = 0;
}

// fn_800145D8 (size: 0x2FC)
// fn_800148D4 (size: 0x1F0)
// fn_80014AC4 (size: 0x1F0)
// fn_80014CB4 (size: 0x2F8)
// fn_80014FAC (size: 0x194)
// fn_80015140 (size: 0x188)
// fn_800152C8 (size: 0x1D8)
// fn_800154A0 (size: 0x398)
// fn_80015838 (size: 0x114)
void fn_8001594C(void) {}
// fn_80015950 (size: 0x13C)
// fn_80015A8C (size: 0xBC)
void fn_80015B48(s32 arg0, s32 arg1, u8 arg2, s32 arg3){

    if (arg2 == 0) {
        GXSetZCompLoc(1);
    }
    else {
        GXSetZCompLoc(0);
    }

    fn_800154A0(1, arg2, arg3, arg0, arg1);
}
// fn_80015BC8 (size: 0xD4)
// fn_80015C9C (size: 0x134)
// fn_80015DD0 (size: 0xE0)
void fn_80015EB0(s32 arg0, s32* arg1, f32 farg0){
    s32 sp14;
    f32 temp_f4;
    void* temp_r31;

    sp14 = *arg1;
    temp_r31 = (void*)(lbl_803990F8 + ((u32)arg0 << 6));

    {
        volatile s32* vcol = &sp14;
        GXInitLightColor(temp_r31, (s32*)vcol);
    }

    temp_f4 = farg0 * lbl_804A2620;

    GXInitLightAttn(
        temp_r31,
        lbl_804A25F8, lbl_804A25F8, lbl_804A25FC,
        temp_f4, lbl_804A25F8, (lbl_804A25FC - temp_f4)
    );

    {
        s32* p = (s32*)(lbl_802F45C0 + ((u32)arg0 << 2));
        GXLoadLightObjImm(temp_r31, *p);
    }
}
// fn_80015F50 (size: 0x180)
// fn_800160D0 (size: 0x1F8)
void fn_800162C8(void){
    UnkEntry_14C* temp_r5;
    s32 unused1;
    if ((s32)lbl_804A0C48 <= 0xB) {
        lbl_804A0D44 = lbl_802F47C0[(u32)lbl_804A0C48];
    } else {
        lbl_804A0D44 = fn_80017048;
    }

    lbl_804A0D30 = 0;
    lbl_804A0D40 = 0;

    fn_80017040();
    {
        u32 idx = (u32)(lbl_80398C00.unkC >> 0x18);
        u8* base = (u8*)(u32)lbl_804A0CF0;
        temp_r5 = *(UnkEntry_14C**)(base + (idx * 0x14C) + 0x18);
    }

    lbl_804A0D3C.unk0 = temp_r5->unk2C;
    lbl_804A0D3C.unk1 = temp_r5->unk2D;
    lbl_804A0D3C.unk2 = temp_r5->unk2E;
    lbl_804A0D3C.unk3 = 0xFF;

    lbl_804A0D48 = 0;
}
// fn_80016378 (size: 0x64)
// fn_800163DC (size: 0x16C)
// fn_80016548 (size: 0x29C)
// fn_800167E4 (size: 0xA4)
// fn_80016888 (size: 0x6C)
// fn_800168F4 (size: 0xB0)
// fn_800169A4 (size: 0xDC)
// fn_80016A80 (size: 0x288)
// fn_80016D08 (size: 0x78)
// fn_80016D80 (size: 0x98)
// fn_80016E18 (size: 0x228)
void fn_80017040(void) {}
void fn_80017044(void) {}
void fn_80017048(void) {}
void fn_8001704C(void) {}
void fn_80017050(void) {}
// fn_80017054 (size: 0x1EC)
void fn_80017240(void) {}
// fn_80017244 (size: 0x254)
// fn_80017498 (size: 0x78)
void fn_80017510(void){
    s32 spC;
    s32 sp8;

    spC = lbl_80498BDC;
    fn_800168F4(8, lbl_802F47A8, &spC, 0x1F4, 0x61);

    sp8 = lbl_80498BDC;
    fn_800168F4(8, lbl_802F47B4, &sp8, 0x1F4, 0x61);
}


void fn_80017574(void) {}

void fn_80017578(void) {}


void fn_8001757C(void) {
    lbl_804A0D68 = 0;
}
// fn_80017588 (size: 0x60)
// fn_800175E8 (size: 0xB0)
// fn_80017698 (size: 0xA0)
// fn_80017738 (size: 0xF8)
// fn_80017830 (size: 0x29C)
// fn_80017ACC (size: 0x50)
// fn_80017B1C (size: 0xF4)
// fn_80017C10 (size: 0x22C)
// fn_80017E3C (size: 0x58)
// fn_80017E94 (size: 0x1E4)
s32 fn_80018078(u8* arg0) {
    if (*arg0 & 1) {
        return 1;
    }
    return 0;
}


s32 fn_80018094(u8* arg0) {
    if (*arg0 & 2) {
        return 1;
    }
    return 0;
}

// fn_800180B0 (size: 0x48)
// fn_800180F8 (size: 0xD0)
void fn_800181C8(void* arg0, void* arg1, s16 arg2){
    UnkDst_800181C8* dst = (UnkDst_800181C8*)arg0;
    UnkSrc_800181C8* src = (UnkSrc_800181C8*)arg1;

    dst->unk0 = (u8)src->unk0;
    dst->unk1 = (u8)src->unk1;
    dst->unk2 = (u8)src->unk2;
    dst->unk4 = arg2;
}

// fn_800181E8 (size: 0xF8)
// fn_800182E0 (size: 0x110)
// fn_800183F0 (size: 0x1A8)
// fn_80018598 (size: 0x108)
// fn_800186A0 (size: 0xA8)
// fn_80018748 (size: 0x138)
// fn_80018880 (size: 0x154)
s32 fn_800189D4(void* arg0){
    if (fn_8003745C() != 0) {
        return 0;
    }

    return ((u8*)arg0)[6] & 0x80;
}


s32 fn_80018A18(void* arg0){
    UnkObj_80018A18* obj = (UnkObj_80018A18*)arg0;
    return obj->unk6 & 0x80;
}
// fn_80018A24 (size: 0x6C)
s32 fn_80018A90(void* arg0, void* arg1, u16* arg2, s8* arg3){
    UnkIn_80018A90*  in  = (UnkIn_80018A90*)arg0;
    UnkOut_80018A90* out = (UnkOut_80018A90*)arg1;

    out->unk0 = in->unk0;
    out->unk1 = in->unk1;
    out->unk2 = in->unk2;

    *arg2 = in->unk4;
    *arg3 = (s8)(in->unk6 & 0x7F);

    return in->unk6 & 0x80;
}


void fn_80018AC8(void* arg0){
    UnkObj_80018AC8* obj = (UnkObj_80018AC8*)arg0;
    fn_8002D484(&lbl_803C2138, obj->unk10);
}


void fn_80018AF4(void* arg0){
    UnkObj_80018AF4* obj = (UnkObj_80018AF4*)arg0;
    fn_8002D4F0(&lbl_803C2138, obj->unk10);
}


s32 fn_80018B20(void* arg0){
    UnkObj_80018B20* obj = (UnkObj_80018B20*)arg0;
    s32 temp_r3;

    temp_r3 = obj->unk18->unk4;

    if (temp_r3 & 1) {
        return 2;
    }
    if (temp_r3 & 2) {
        return 1;
    }
    return 0;
}


s32 fn_80018B50(void* arg0){
    UnkObj_80018B50* obj = (UnkObj_80018B50*)arg0;
    u32 v = (u32)obj->unk10 & 0xFF;

    if ((v == 0x1C) && (fn_80037234() == 0)) {
        return 1;
    }
    return 0;
}


void fn_80018B94(void* arg0){
    UnkObj_80018B94* obj = (UnkObj_80018B94*)arg0;

    obj->unk14 = (s32)(obj->unk14 | 0x20);

    if (lbl_804A0C48 == 2) {
        u8* base = (u8*)lbl_803C2E10 + 0xA0;
        u32 off  = ((u32)obj->unk10 << 1) & 0x1FE;

        *(u16*)(base + off) = (u16)(*(u16*)(base + off) | 4);
    }
}


void fn_80018BD0(void* arg0){
    UnkObj_80018BD0* obj = (UnkObj_80018BD0*)arg0;

    obj->unk14 = (s32)(obj->unk14 | 0x40);

    if (lbl_804A0C48 == 2) {
        u8* base = (u8*)lbl_803C2E10 + 0xA0;
        u32 off  = ((u32)obj->unk10 << 1) & 0x1FE;

        *(u16*)(base + off) = (u16)(*(u16*)(base + off) | 8);
    }
}
// fn_80018C0C (size: 0xBCC)
// fn_800197D8 (size: 0xC4)
// fn_8001989C (size: 0x10C)
// fn_800199A8 (size: 0xBC)
void fn_80019A64(void) {
    lbl_804A0D73 = 0;
    lbl_804A0D74 = 0;
}

// fn_80019A74 (size: 0x11C)
// fn_80019B90 (size: 0x11C)
void fn_80019CAC(s32 arg0){

    fn_8001F534(arg0, 0xF, (void*)lbl_802F4A70);
    fn_8001F76C(arg0, 6, (void*)lbl_802F4B4C);
}
// fn_80019CF8 (size: 0x200)
// fn_80019EF8 (size: 0x19C)
// fn_8001A094 (size: 0x2C0)
// fn_8001A354 (size: 0x5A0)
void fn_8001A8F4(void){
    u8  stack_pad[0x08];
    s32 byteOff;
    s32 count;
    u8* tbl;

    stack_pad[0] = 0;

    count = 0;
    if (count) {
        stack_pad[0] = 0;
    }
    byteOff = 0;

    tbl = (u8*)lbl_802F4B64;

    goto test;

    loop:
    {
        UnkElem_8001A8F4* e;
        UnkTblEntry_8001A8F4* t;

        e = (UnkElem_8001A8F4*)(lbl_804A0D7C + byteOff);
        t = (UnkTblEntry_8001A8F4*)(tbl + ((s32)e->unk1 * 0x14));

        fn_8001F880(lbl_804A0D78, e->unk64);
        e->unk64->unk11C = (s32)t->unk12;
        fn_8001E594(e->unk64);
        fn_8001E890(e->unk64, (void*)((u8*)e + 0x2C), e->unk5C, e->unk60);

        byteOff += 0x68;
        count   += 1;
    }

    test:
    if (count < (s32)lbl_804A0D88) {
        goto loop;
    }
}
// fn_8001A988 (size: 0x1E4)
s32 fn_8001AB6C(s16 arg0, s32 arg1, s8 arg2){
    UnkEntry_8001AB6C* temp_r31;

    if ((u16)lbl_804A0D88 == 0) {
        return 0;
    }

    temp_r31 = (UnkEntry_8001AB6C*)(lbl_804A0D7C + ((s32)arg0 * 0x68));

    if (arg2 == 0) {
        return temp_r31->unkC;
    }

    fn_8001A988(0, (void*)temp_r31, (u8)arg0, arg1, arg2);
    return temp_r31->unkC;
}


s32 fn_8001ABE0(s16 arg0, s32 arg1, s8 arg2){
    UnkEntry_8001ABE0* temp_r31;

    if ((u16)lbl_804A0D88 == 0) {
        return 0;
    }

    temp_r31 = (UnkEntry_8001ABE0*)((u8*)(lbl_804A0D7C) + ((s32)arg0 * 0x68));

    if (arg2 == 0) {
        return temp_r31->unkC;
    }

    fn_8001A988(1, (void*)temp_r31, (u8)arg0, arg1, arg2);
    return temp_r31->unkC;
}
// fn_8001AC54 (size: 0x5C)
// fn_8001ACB0 (size: 0x3C)
s32 fn_8001ACEC(s16 arg0, u8* arg1, u8* arg2){
    UnkD7C_Entry* e;

    e = (UnkD7C_Entry*)(lbl_804A0D7C + (arg0 * 0x68));

    *arg1 = e->unk0;
    *arg2 = e->unk1;

    e->unkC = e->unkC | 0x8000;

    return e->unkC & 0x400;
}

// fn_8001AD24 (size: 0x110)
s8 fn_8001AE34(s16 arg0, u8 arg1){
    u32 pad0;

    if (lbl_804A0D88 == 0) {
        return -1;
    }

    if (fn_80065320(0x53) == 1) {
        return -1;
    }

    {
        s16 idx = arg0;
        u8* p = (u8*)(lbl_804A0D7C + ((s32)idx * 0x68));

        if (arg1 == 0x28) {
            if (*p == 0x28) {
                return (s8)lbl_80399710.unk58;
            }
        }
    }

    return -1;
}


s8 fn_8001AED4(u32 arg0){
    s32 off;
    s8  var_r7;
    u8  temp_r0;

    var_r7 = 0;

    if ((arg0 == 0xFF) || ((u16)lbl_804A0D88 == 0)) {
        return 0;
    }

    off = ((s32)arg0 * 2) & 0x1FE;
    temp_r0 = lbl_80399510[off + 0];

    if (*(u32*)(lbl_804A0D7C + ((s32)temp_r0 * 0x68) + 0x0C) & 8) {
        var_r7 = 1;
    }

    temp_r0 = lbl_80399510[off + 1];

    if (temp_r0 == 0xFF) {
        return var_r7;
    }

    if (*(u32*)(lbl_804A0D7C + ((s32)temp_r0 * 0x68) + 0x0C) & 8) {
        var_r7 += 1;
    }

    if ((s8)var_r7 == 2) {
        return 1;
    }

    return 0;
}


s32 fn_8001AF78(u8 arg0, u8* arg1, u8* arg2){
    u8* p;

    if (((u16)lbl_804A0D88 == 0) && (arg0 >= 0xFFU)) {
        return 0;
    }

    p = (u8*)&lbl_80399710 + (((s32)arg0 * 2) & 0x1FE);

    *arg1 = p[0];
    *arg2 = p[1];

    return 0;
}


s32 fn_8001AFC0(s32 arg0, UnkOut_8001AFC0* arg1){
    u8* p;
    u8  a;
    u8  b;
    register s32 ret;

    if ((u16)lbl_804A0D88 == 0) {
        return 0;
    }

    p = (u8*)&lbl_80399710 + ((arg0 * 2) & 0x1FE);
    a = p[0];

    if (a == 0xFF) {
        return 0;
    }

    arg1->unk0 = (s32)(lbl_804A0D7C + ((s32)a * 0x68));
    ret = 1;
    b = p[1];

    if (b == 0xFF) {
        goto out;
    }

    arg1->unk4 = (s32)(lbl_804A0D7C + ((s32)b * 0x68));
    ret = 2;

    out:
    return ret;
}

// fn_8001B030 (size: 0x10C)
// fn_8001B13C (size: 0x58)
void fn_8001B194(void){
    Frame_8001B194 fr;

    lbl_804A0D8A = 0;
    lbl_804A0D8C = 0;
    lbl_804A0D90 = 0;

    fn_800ABD40(&fr.sp8);

    fr.sp58 = 1;

    fn_800ABECC(0, 0x12, &fr.sp8);
}


void fn_8001B1E0(void) {
    lbl_804A0D8A = 0;
    lbl_804A0D8C = 0xA;
    lbl_804A0D90 = 0;
}


s32 fn_8001B1F8(u8 arg0){
    if (lbl_804A0D8A != 0) {
        return 1;
    }

    if ((lbl_804A0D88 == 0) || (arg0 == 0xFF)) {
        return 0;
    }

    return (s32)((*(u32*)(lbl_804A0D7C + ((s32)arg0 * 0x68) + 0x0C)) & (u32)0x10000);
}
// fn_8001B244 (size: 0x2A0)
// fn_8001B4E4 (size: 0x318)
// fn_8001B7FC (size: 0x238)
// fn_8001BA34 (size: 0x580)
// fn_8001BFB4 (size: 0x300)
// fn_8001C2B4 (size: 0xF0)
// fn_8001C3A4 (size: 0xD8)
// fn_8001C47C (size: 0xDC)
// fn_8001C558 (size: 0xFC)
void fn_8001C654(void){
    if ((u16)lbl_804A0D88 != 0) {
        fn_800B8758();
        fn_8001F1F8(lbl_804A0D78, 1);
        __destroy_new_array(lbl_804A0D80, fn_8001E4E8);
        fn_8000604C(lbl_804A0D84);
        fn_8000604C(lbl_804A0D7C);
    }
}

// fn_8001C6AC (size: 0x98)
// fn_8001C744 (size: 0x58)
// fn_8001C79C (size: 0x5C)
// fn_8001C7F8 (size: 0x22C)
u8 fn_8001CA24(void** arg0){
    register u8 t = lbl_804A0CD0;
    register s8 idx = (s8)t;

    {
        u8* base = lbl_80399910;
        u8* p = base + (idx << 6);
        *arg0 = (void*)p;
    }

    {
        register u8 t2 = lbl_804A0CD0;
        register s8 idx2 = (s8)t2;

        u8* flags = (u8*)&lbl_804A0D98;

        return flags[idx2];
    }
}


u8 fn_8001CA54(void** arg0, u8 arg1){
    u32 off = (u32)((arg1 << 6) & 0x3FC0);

    *arg0 = (void*)(lbl_80399910 + off);
    return ((u8*)&lbl_804A0D98)[arg1];
}


s32 fn_8001CA78(u8 arg0, s32 arg1){
    if (arg1 == -1) {
        u8  t   = lbl_804A0CD0;
        s32* tbl = lbl_80399B10;
        u32 off = (u32)arg0 * 0xC;

        s8  idx = (s8)t;
        s32 base_as_int = tbl[(s32)idx];
        u16 v = *(u16*)((u8*)base_as_int + off);
        return (s32)(v & 1);
    }
    else {
        s32* tbl = lbl_80399B10;

        u32 off = (u32)arg0 * 0xC;

        s32 base_as_int = tbl[arg1];

        u16 v = *(u16*)((u8*)base_as_int + off);
        return (s32)(v & 1);
    }
}


u8 fn_8001CAD8(u8 arg0){
    s8  sidx = (s8)lbl_804A0CD0;
    u32 off  = (u32)arg0 * 0xC;

    s32 base_as_int = lbl_80399B10[(s32)sidx];
    u8* p = (u8*)base_as_int;
    p = p + off;

    return *(p + 3);
}

// fn_8001CB08 (size: 0x24)
// fn_8001CB2C (size: 0x54)
void fn_8001CB80(void) {
    lbl_804A0DA1 = 0;
    lbl_804A0DA0 = 0;
}


void fn_8001CB90(void) {
    lbl_804A0DA1 = 0;
}


void fn_8001CB9C(u32 arg0) {
    if (arg0 == 0U) {
        lbl_804A0DA1 = 0;
        return;
    }
    lbl_804A0DA4 = arg0;
    lbl_804A0DA1 = 1;
}


void* fn_8001CBC0(void* arg0){
    Unk_8001CBC0* p = (Unk_8001CBC0*)arg0;
    u8 zero = 0;

    p->unk0 = zero;
    fn_8001CC04(arg0);
    p->unk1 = zero;
    return arg0;
}


void fn_8001CC04(void* arg0){
    Unk_8001CC04* p = (Unk_8001CC04*)arg0;
    p->unkC = 0;
}
// fn_8001CC10 (size: 0x19C)
// fn_8001CDAC (size: 0x15C)
void fn_8001CF08(s32 unused, s32 arg1){
    s32 r31;

    (void)unused;
    r31 = (s32)fn_80006A3C(arg1);
    fn_8001D050(r31, fn_80006A44(arg1), (void*)0);
}
// fn_8001CF5C (size: 0xF4)
// fn_8001D050 (size: 0xCC)
// fn_8001D11C (size: 0xF8)
// fn_8001D214 (size: 0x128)
// fn_8001D33C (size: 0x11C)
// fn_8001D458 (size: 0x58)
// fn_8001D4B0 (size: 0x40)
void fn_8001D4F0(void* arg0, s16 arg1){
    Unk_8001D4F0_Arg0* a;
    s32 off;
    u8* base;
    u8  v;

    a = (Unk_8001D4F0_Arg0*)arg0;

    if ((u8)lbl_804A0DA8 == 0) {
        off  = (s32)arg1;
        base = a->unk38;
        off  = off * 0x18;
        base = base + off;
        GXSetCullMode(*(u8*)(base + 9));
        return;
    }

    off  = (s32)arg1;
    base = a->unk38;
    off  = off * 0x18;
    base = base + off;
    v = *(u8*)(base + 9);

    switch ((s32)v) {
        case 2:
            GXSetCullMode((u8)1);
            return;
        case 1:
            GXSetCullMode((u8)2);
            return;
        case 0:
            GXSetCullMode((u8)0);
            return;
        default:
            return;
    }
}


void fn_8001D588(void* arg0, s16 arg1){
    Unk_8001D588_Arg0* a;
    u8* base;
    Unk_8001D588_Entry18* e;

    a = (Unk_8001D588_Arg0*)arg0;

    base = a->unk38;
    e = (Unk_8001D588_Entry18*)(base + ((s32)arg1 * 0x18));

    GXCallDisplayList((void*)(base + e->unkC), (s32)(e->unk2 << 5), (s32)base);
}

// fn_8001D5C8 (size: 0x1C4)
// fn_8001D78C (size: 0x1C)
void fn_8001D7A8(void* arg0, s16 arg1, void* arg2){
    Unk_8001D7A8_Arg0* a = (Unk_8001D7A8_Arg0*)arg0;
    Unk_8001D7A8_Out4* o = (Unk_8001D7A8_Out4*)arg2;

    if (a->unk1 & 1) {
        o->unk0 = a->unk48;
        o->unk1 = a->unk49;
        o->unk2 = a->unk4A;
        o->unk3 = a->unk4B;
        return;
    }

    {
        register s32 r6;
        register s32 r0;
        u8* p;

        r0 = (s32)arg1;
        r6 = r0 * 0x28;

        p = (u8*)a->unk34;
        p = p + r6;
        o->unk0 = p[3];

        r0 = a->unk34;
        p = (u8*)r0;
        p = p + r6;
        o->unk1 = p[4];

        r0 = a->unk34;
        p = (u8*)r0;
        p = p + r6;
        o->unk2 = p[5];

        r0 = a->unk34;
        p = (u8*)r0;
        p = p + r6;
        o->unk3 = p[6];
    }
}


void fn_8001D824(void* arg0, void* arg1){
    Unk_8001D824_Arg0* a = (Unk_8001D824_Arg0*)arg0;
    Unk_8001D824_In4*  b = (Unk_8001D824_In4*)arg1;

    a->unk48 = b->unk0;
    a->unk49 = b->unk1;
    a->unk4A = b->unk2;
    a->unk4B = b->unk3;

    a->unk1 = (u8)(a->unk1 | 1);
}
// fn_8001D854 (size: 0x74)
// fn_8001D8C8 (size: 0x154)
void fn_8001DA1C(void* arg0, void* arg1){
    Unk_8001DA1C_Arg0* a = (Unk_8001DA1C_Arg0*)arg0;
    Unk_8001DA1C_Arg1* b = (Unk_8001DA1C_Arg1*)arg1;

    a->unk4C = b->unk0;
    a->unk50 = b->unk4;
    a->unk54 = b->unk8;

    {
        f32 z = lbl_804A2700;

        a->unk58 = z;
        a->unk5C = b->unk10;
        a->unk60 = b->unk14;
        a->unk64 = b->unk18;
        a->unk68 = z;
        a->unk6C = b->unk20;
        a->unk70 = b->unk24;
        a->unk74 = b->unk28;
        a->unk78 = z;
    }
}


void fn_8001DA78(void* arg0){
    Unk_8001DA78_Arg0* a = (Unk_8001DA78_Arg0*)arg0;

    a->unk0 = 0;
    a->unk4 = 0;
}
// fn_8001DA88 (size: 0x64)
// fn_8001DAEC (size: 0xAC)
// fn_8001DB98 (size: 0x110)
// fn_8001DCA8 (size: 0x750)
void fn_8001E3F8(void* arg0){
    Unk_8001E3F8_Arg0* a = (Unk_8001E3F8_Arg0*)arg0;

    a->unk0   = 0;
    a->unk11C = 0;
    a->unk120 = 0;
    a->unk124 = 0;
    a->unk310 = lbl_804A2750;

    fn_8018AFA0((u8*)a + 0x94, 0, 1, 0, a);
}
// fn_8001E448 (size: 0x70)

void fn_8001E4B8(void* arg0){
    Unk_8001E4B8_Arg0* a = (Unk_8001E4B8_Arg0*)arg0;

    if (a->unk0 & 2U) {
        __dla__FPv(a->unk128);
    }
}
// fn_8001E4E8 (size: 0x60)
// fn_8001E548 (size: 0x1C)
void fn_8001E564(void* arg0, s32 arg1, s32 arg2){
    Unk_8001E564_Arg0* a = (Unk_8001E564_Arg0*)arg0;

    {
        s32 idx = a->unk124;
        u8* base = (u8*)a;
        base += (idx << 2);
        ((Unk_8001E564_Entry*)base)->at44 = arg1;
    }

    {
        s32 idx = a->unk124;
        u8* base = (u8*)a;
        base += (idx << 2);
        ((Unk_8001E564_Entry*)base)->at6C = arg2;
    }

    {
        s32 idx = a->unk124;
        a->unk124 = idx + 1;
    }
}


void fn_8001E594(void* arg0){
    Unk_8001E594* a = (Unk_8001E594*)arg0;
    s32 unused1;

    {
        s32 idx = a->unk11C;
        u8* base = (u8*)a;
        base += (idx << 2);

        a->unk30C = (s32)((Unk_Entry4_ObjC*)base)->unk4->unkC;
    }

    if (a->unk30C < 0xA) {
        a->unk128 = (void*)((u8*)a + 0x12C);
    }
    else {
        a->unk128 = __nwa__FUl((u32)(a->unk30C * 0x30));
        a->unk0 |= 2;
    }

    a->unk0 |= 1;
}
// fn_8001E610 (size: 0x280)
// fn_8001E890 (size: 0x1F4)
// fn_8001EA84 (size: 0x270)
void fn_8001ECF4(Unk_8001ECF4* arg0){
    if (arg0->unk0 & 4) {
        GXSetZMode(0, 3, 1);
    }

    {
        Unk_Entry4_s32* e = (Unk_Entry4_s32*)((u8*)arg0 + (arg0->unk11C << 2));
        fn_80015950(e->unk4, arg0->unk128, 0, 0xFF);
    }
    {
        Unk_Entry4_s32* e = (Unk_Entry4_s32*)((u8*)arg0 + (arg0->unk11C << 2));
        fn_80015950(e->unk4, arg0->unk128, 1, 0xFF);
    }

    if (arg0->unk0 & 4) {
        GXSetZMode(1, 3, 1);
    }
}


void fn_8001ED94(void* arg0, u8 arg1){
    register u8 r31_arg1 = arg1;
    register Unk_8001ED94_Arg0* r30 = (Unk_8001ED94_Arg0*)arg0;

    if ((u32)r31_arg1 == 0) {
        return;
    }

    if (r30->unk0 & 4) {
        GXSetZMode(1, 3, 0);
    }

    {
        register u8* p = (u8*)r30 + ((u32)r30->unk11C << 2);
        fn_80015950(*(s32*)(p + 4), r30->unk128, 2, r31_arg1);
    }

    if (r30->unk0 & 4) {
        GXSetZMode(1, 3, 1);
    }
}


void fn_8001EE28(void* arg0, s32 arg1){
    Unk_8001EE28_Arg0* a = (Unk_8001EE28_Arg0*)arg0;

    if (a->unk0 & 4) {
        GXSetZMode(0, 3, 1);
    }

    fn_80015B48(arg1, a->unk128, 0, 0xFF);
    fn_80015B48(arg1, a->unk128, 1, 0xFF);

    if (a->unk0 & 4) {
        GXSetZMode(1, 3, 1);
    }
}

// fn_8001EEBC (size: 0x94)
s32 fn_8001EF50(s32 arg0, s32 arg1){
    Unk_8001F390_Obj* p;

    p = (Unk_8001F390_Obj*)__nw__FUl(0x40U);
    if (p != 0) {
        fn_8001F928(p);
    }

    /* arg1 is really a code pointer; cast it to the right method type */
    fn_8001F390(p, arg0, (Unk_8001F390_Method)(u32)arg1);

    return (s32)p;
}



s32 fn_8001EFB8(s32 arg0, s32 arg1){
    s32 temp_r3;

    temp_r3 = __nw__FUl(0x40U);
    if (temp_r3 != 0) {
        fn_8001F928((void*)temp_r3);
    }

    fn_8001F3E8((void*)temp_r3, arg0, (Unk_8001F3E8_Method)(u32)arg1);

    return temp_r3;
}



void fn_8001F020(void* unused_r3, s32 arg1){
    Unk_8001F020_Obj* obj;
    s32 a;
    u8 frame_pad[8];

    (void)unused_r3;
    (void)frame_pad;

    a = arg1;

    obj = fn_80006A3C(a);

    obj->unk8 = fn_80006A54(a);
    obj->unk4(obj);
    obj->unk2 = 2;
}
// fn_8001F080 (size: 0xA4)
// fn_8001F124 (size: 0xD4)
// fn_8001F1F8 (size: 0xBC)
// fn_8001F2B4 (size: 0xDC)
void fn_8001F390(Unk_8001F390_Obj* arg0, s32 arg1, Unk_8001F390_Method arg2){
    arg0->unk2 = 1;
    arg0->unk4 = arg2;
    arg0->unk8 = arg1;
    arg0->unk0 = (u16)(arg0->unk0 | 1);
    arg0->unk4(arg0);
    arg0->unk2 = 2;
}


void fn_8001F3E8(void* arg0, s32 arg1, Unk_8001F3E8_Method arg2){
    Unk_8001F3E8_Obj* self = (Unk_8001F3E8_Obj*)arg0;

    self->unk2 = 1;
    self->unk4 = arg2;
    self->unk8 = fn_8006624C(arg1);
    self->unk4(self);
    self->unk2 = 2;
}


void fn_8001F440(void* arg0, s16 arg1){
    volatile u8 sp_pad[8];
    Unk_8001F440_Arg0* self = (Unk_8001F440_Arg0*)arg0;
    (void)sp_pad;

    if (arg1 != 0) {
        void* mem = __nwa__FUl((u32)(((s32)(s16)arg1 * 0x7C) + 8));

        self->unkC = __construct_new_array(
            mem,
            (CtorFnRtl)fn_8001CBC0,
                                           (CtorFnRtl)0,
                                           0x7C,
                                           (s32)(s16)arg1
        );
    }
}
// fn_8001F4A4 (size: 0x90)
// fn_8001F534 (size: 0xF8)
void fn_8001F62C(void* arg0, s16 arg1){
    volatile u8 sp_pad[8];
    Unk_8001F62C_Arg0* a = (Unk_8001F62C_Arg0*)arg0;
    (void)sp_pad;

    if (arg1 != 0) {
        void* mem = __nwa__FUl((u32)((arg1 * 0x24) + 8));
        a->unk10 = __construct_new_array(mem, (CtorFnRtl)fn_8001DA78, (CtorFnRtl)fn_8001DA88, 0x24, (s32)arg1);
        a->unk14 = __nwa__FUl((u32)(arg1 * 4));
    }
}
// fn_8001F6A0 (size: 0xCC)
// fn_8001F76C (size: 0x114)
// fn_8001F880 (size: 0xA8)
void fn_8001F928(void* arg0){
    Unk_8001F928_Obj* obj = (Unk_8001F928_Obj*)arg0;

    obj->unk1C = 0;
    obj->unk20 = 0;
    obj->unk24 = 0;
    obj->unk28 = 0;
    obj->unk2C = 0;
    obj->unk30 = 0;
    obj->unk34 = 0;
    obj->unk38 = 0;

    obj->unk0  = 0;
    obj->pad2  = 0;

    obj->unk3C = 0;
    obj->unk3D = 0;

    obj->unkC  = 0;
    obj->unk10 = 0;
    obj->unk14 = 0;
    obj->unk8  = 0;
}


void fn_8001F970(void) {
    lbl_804A0DB0 = 0;
}


void fn_8001F97C(s32 arg0, s32 arg1, s32 arg2){
    UnkHeader_0C* h;
    h = (UnkHeader_0C*)(u32)lbl_80399B60[arg0 - 1];
    fn_8001E548(arg2, h->unkC + (arg1 * 0x7C));
}

// fn_8001F9C0 (size: 0x64)
// fn_8001FA24 (size: 0xB4)
void fn_8001FAD8(void* arg0, s32 arg1, FnVoid0 arg2){
    Unk_8001FAD8_Arg0* a = (Unk_8001FAD8_Arg0*)arg0;

    a->unk4 = arg1;
    a->unkC = 0;

    if (arg2 != NULL) {
        lbl_804A0DB8 = (Unk_804A0DB8_Obj*)a;
        arg2();
    }
}

// fn_8001FB18 (size: 0xA8)
// fn_8001FBC0 (size: 0x60)
// fn_8001FC20 (size: 0x40)
void fn_8001FC60(void* arg0, s8 arg1){
    ((Unk_8001FC60_Arg0*)arg0)->unk10 = arg1;
}
// fn_8001FC68 (size: 0x210)
// fn_8001FE78 (size: 0xD0)
// fn_8001FF48 (size: 0xE8)
void fn_80020030(void* arg0, f32 farg0){
    ((Unk_80020030_Arg0*)arg0)->unkA8 = lbl_804A27B8 * farg0;
}

// fn_80020040 (size: 0xD0)
// fn_80020110 (size: 0x198)
void fn_800202A8(s32 arg0){
    lbl_804A0DB8 = (Unk_804A0DB8_Obj*)(u32)arg0;
}

// fn_800202B0 (size: 0x13C)
// fn_800203EC (size: 0x14C)
void fn_80020538(void){
    __dl__FPv(lbl_80399BE0.unk0);
    __dl__FPv(lbl_80399BE0.unk4);
    __dl__FPv(lbl_80399BE0.unk8);
}


void fn_8002057C(void){
    register UnkPairF32* ddc = &lbl_804A0DDC;
    register UnkPairF32* de4 = &lbl_804A0DE4;
    register Unk_802F4E18* tbl;
    register f32 f0 = lbl_804A27D0;
    register s32 zero = 0;
    register s32 addr;

    addr = (s32)&lbl_802F4E18;
    tbl  = (Unk_802F4E18*)addr;

    lbl_804A0DDC.unk0 = f0;
    ddc->unk4 = f0;

    lbl_804A0DE4.unk0 = f0;
    de4->unk4 = f0;

    lbl_804A0DF0 = f0;
    lbl_804A0DEC = f0;
    lbl_804A0DD8 = (s8)zero;

    lbl_804A0DC0 = tbl->unk38;
    lbl_804A0DC4 = tbl->unk3C;
    lbl_804A0DC8 = tbl->unk40;
    lbl_804A0DCC = tbl->unk44;

    lbl_804A0DFC = zero;
}


void fn_800205D8(s32 arg0){
    lbl_804A0DFC = arg0;

    switch (arg0) {
        case 3:
            lbl_80399C20.unk8 = 0;
            return;

        case 5:
            fn_8002418C();
            lbl_804A0DF8 = 0;
            /* fallthrough */
            case 4:
                return;
    }
}


void fn_8002063C(void) {
    lbl_804A0DFC = 0;
}
// fn_80020648 (size: 0xC0)
// fn_80020708 (size: 0x19C)
// fn_800208A4 (size: 0x238)
// fn_80020ADC (size: 0x120)
// fn_80020BFC (size: 0x138)
// fn_80020D34 (size: 0x184)
// fn_80020EB8 (size: 0xE4)
// fn_80020F9C (size: 0x2CC)
// fn_80021268 (size: 0x120)
// fn_80021388 (size: 0xDC)
// fn_80021464 (size: 0x1C8)
void fn_8002162C(void){
    lbl_804A0DB8->unkE0 = 0;
}
// fn_8002163C (size: 0xD8)
void fn_80021714(void){
    lbl_804A0DB8->unkE0 = 0;
}

// fn_80021724 (size: 0x164)
// fn_80021888 (size: 0x174)
void fn_800219FC(void){
    lbl_804A0CF8 = ((Unk_804A0DB8_Obj*)lbl_804A0DB8)->unkE8;
    fn_80021724(lbl_804A0DB8);
    {
        Unk_804A0DB8_Obj* p = (Unk_804A0DB8_Obj*)lbl_804A0DB8;
        p->unkE0 = p->unkE0 + 1;
    }
}


void fn_80021A38(void){
    fn_8001FC60((void*)lbl_804A0DB8, (s8)0);
    lbl_804A0DB8->unkE0 = 0;
}
// fn_80021A6C (size: 0x330)
// fn_80021D9C (size: 0x114)
void fn_80021EB0(void){
    fn_8001FC60((void*)lbl_804A0DB8, (s8)0);
    lbl_804A0DB8->unkE0 = 0;
}
// fn_80021EE4 (size: 0x354)
// fn_80022238 (size: 0x338)
// fn_80022570 (size: 0x274)
// fn_800227E4 (size: 0x114)
// fn_800228F8 (size: 0x150)
// fn_80022A48 (size: 0x10C)
