/* autogenerated decompilation stub */
/* source asm: auto_03_800D355C_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_800D355C (size: 0x8)
// fn_800D3564 (size: 0x4)
// fn_800D3568 (size: 0x64)
// fn_800D35CC (size: 0x64)
// fn_800D3630 (size: 0x8)
// fn_800D3638 (size: 0x30)
// fn_800D3668 (size: 0x98)
// fn_800D3700 (size: 0x8)
// fn_800D3708 (size: 0x58)
// fn_800D3760 (size: 0x8)
// fn_800D3768 (size: 0x8)
