/* autogenerated decompilation stub */
/* source asm: auto_03_800D410C_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_800D410C (size: 0x8)
// fn_800D4114 (size: 0x118)
// fn_800D422C (size: 0x64)
// fn_800D4290 (size: 0x64)
// fn_800D42F4 (size: 0x44)
// fn_800D4338 (size: 0xC)
// fn_800D4344 (size: 0x48)
// fn_800D438C (size: 0x28)
// fn_800D43B4 (size: 0x74)
// fn_800D4428 (size: 0xFC)
// fn_800D4524 (size: 0x64)
// fn_800D4588 (size: 0xC4)
// fn_800D464C (size: 0x13C)
// fn_800D4788 (size: 0x60)
// fn_800D47E8 (size: 0x10)
// fn_800D47F8 (size: 0x10)
// fn_800D4808 (size: 0x134)
// fn_800D493C (size: 0xB0)
// fn_800D49EC (size: 0x94)
