/* autogenerated decompilation stub */
/* source asm: auto_03_801048E0_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_801048E0 (size: 0x8)
// fn_801048E8 (size: 0x8)
// fn_801048F0 (size: 0x8)
// fn_801048F8 (size: 0x8)
// fn_80104900 (size: 0x8)
// fn_80104908 (size: 0x8)
// fn_80104910 (size: 0x138)
// fn_80104A48 (size: 0x64)
// fn_80104AAC (size: 0x7C)
// fn_80104B28 (size: 0x8)
// fn_80104B30 (size: 0x8)
// fn_80104B38 (size: 0x58)
// fn_80104B90 (size: 0x238)
// fn_80104DC8 (size: 0x138)
// fn_80104F00 (size: 0x6C)
// fn_80104F6C (size: 0x16C)
// fn_801050D8 (size: 0x64)
