/* autogenerated decompilation stub */
/* source asm: auto_03_8000C650_text.s */
#include "auto_03_8000C650_text.h"
/* FUNCTIONS TO DECOMPILE */

// fn_8000C650 (size: 0xB0)
void fn_8000C700(void) {
    if (lbl_804A0C58 != 1) {
        fn_80038EF0();
    }
}


void fn_8000C72C(void) {
    fn_801886F0(0);
    lbl_804A0FB0 = 1;
    fn_80007D38(2);
}


void fn_8000C760(void) {
    lbl_804A0C08 = 0;
    lbl_804A0C44 = 0;
    fn_801886F0(0);
    lbl_804A0FB0 = 1;
    fn_80007D38(2);
    fn_80038F94();
}


s32 fn_8000C7A4(void){
    if (lbl_80398770[0] != 0U) {
        return 0;
    }
    if (lbl_804A0C08 != 0) {
        return 0;
    }
    return 1;
}
// fn_8000C7D8 (size: 0xE0)
// fn_8000C8B8 (size: 0xB4)
// fn_8000C96C (size: 0xD8)
// fn_8000CA44 (size: 0xA0)
void fn_8000CAE4(void){
    lbl_804A0FB0 = 0;
    fn_80007D38(1);
    fn_80188318(0x3804);
    fn_80070F84();
    fn_8005452C(lbl_804A0C68);
    lbl_804A0C6C = 1;
}


void fn_8000CB2C(void) {
    if ((s32) lbl_804A0C44 == 5) {
        if ((s32) lbl_804A0C6C == 0) {
            lbl_804A0FB0 = 0;
            fn_80007D38(1);
            fn_80188318(0x3804);
            fn_80070F84();
            fn_8005452C(lbl_804A0C68);
            lbl_804A0C6C = 1;
            return;
        }
        if (fn_80054688() != 0) {
            fn_80188318(0x3804);
            fn_8000CBD8();
        }
    }
}


void fn_8000CBA8(void) {
    if ((s32) lbl_804A0C6C != 0) {
        fn_8005D300();
        fn_800546AC();
    }
}


void fn_8000CBD8(void){
    lbl_804A0C44 = 0;
    lbl_804A0FB0 = 1;
    fn_80054750();
    fn_801868B8((u8)lbl_804A0B88, 0);
    fn_80007D38(2);
    lbl_804A0C6C = 0;
}


void fn_8000CC2C(void){
    if ((s8)lbl_804A0C74 == 0) {
        lbl_804A0C70 = 0;
        lbl_804A0C74 = 1;
    }

    if ((s32)lbl_804A0C44 == 6) {
        if ((s32)lbl_804A0C70 != 0) {
            lbl_804A0C70 = 0;
            lbl_804A0C44 = 0;
            fn_801853A4();
            return;
        }

        if (lbl_804A0BF8->unk18 & 0x200) {
            lbl_804A0C70 = 1;
        }

        fn_801853A8();
    }
}


void fn_8000CCAC(void){
    if ((s8)lbl_804A0C7C == 0) {
        lbl_804A0C78 = 0;
        lbl_804A0C7C = 1;
    }

    if ((s32)lbl_804A0C44 == 7) {
        if ((s32)lbl_804A0C78 != 0) {
            lbl_804A0C78 = 0;
            lbl_804A0C44 = 0;
            fn_80050D10();
            return;
        }

        if (fn_80050C48() != 0) {
            lbl_804A0C78 = 1;
        }
    }
}


void fn_8000CD24(void){
    if ((s32)lbl_80498B2C == 2) {
        if (fn_80065320(7) != 0) {
            lbl_80498B28 = 0;
        }
        else {
            lbl_80498B28 = 0x4C;
        }
    }
    else {
        lbl_80498B28 = 0x4C;
    }

    fn_8005CE40();

    if ((s32)lbl_80498B28 == 0) {
        fn_801870EC(0xC0000000u);
    }
    else {
        fn_801870EC(0xC0000001u);
    }

    do {
    } while (fn_80187190() == 0);

    fn_801138C0();
    fn_80113094(lbl_80498B28);
}


s32 fn_8000CDBC(void){
    s32 ret;

    switch ((s32)lbl_804A1880) {
        case 2:
            fn_8011325C();
            fn_801872F0(0);
            lbl_804A1880 = 4;
            goto ret4;

        case 4:
            if (fn_801132CC() != 0) {
                lbl_804A0C48 = 2;
                ret = lbl_80498B2C;
                goto done;
            }
            goto ret4;

        case 3:
        default:
            goto ret4;
    }

    ret4:
    ret = 4;

    done:
    return ret;
}


void fn_8000CE38(void) {
    if ((s32) lbl_804A1880 == 4) {
        fn_80113474();
    }
}


void fn_8000CE64(void) {
    lbl_804A1880 = 0;
    fn_80186E48(0);
    fn_80113838();
}


void fn_8000CE94(void) {
    fn_8000F418();
}


s32 fn_8000CEB4(void) {
    if (fn_8000F564() != 0) {
        return 6;
    }
    return 5;
}


void fn_8000CEE8(void) {
    fn_8000F818();
}


void fn_8000CF08(void) {
    do {

    } while (fn_80006A5C() != 0);
}


void fn_8000CF30(s32 unused, s32 arg1){
    s32* temp_r31;

    (void)unused;
    temp_r31 = fn_80006A3C(arg1);
    *temp_r31 = fn_80006A44(arg1);
}
// fn_8000CF78 (size: 0x118)
s32 fn_8000D090(void) {
    return lbl_804A0C80;
}
// fn_8000D098 (size: 0x458)
// fn_8000D4F0 (size: 0xA2C)
// fn_8000DF1C (size: 0x3B4)
void fn_8000E2D0(void){
    fn_8000604C(lbl_80398AA0.unk0);
    fn_8000604C(lbl_80398AA0.unk1C);
    fn_8000604C(lbl_80398AA0.unk38);
    fn_8000604C(lbl_80398AA0.unk54);
    fn_8000604C(lbl_80398AA0.unk70);
    fn_8000604C(lbl_80398AA0.unk8C);
    fn_8000604C(lbl_80398AA0.unkA8);
    fn_80056E08();
}


void fn_8000E338(void* unused, UnkArg_8000E338* arg1){
    void* buf;
    JKRMemArchive* arc;
    JKRHeap* heap;
    s32 unused1;

    (void)unused;

    heap = fn_80007098(arg1->unk64);
    buf  = alloc__7JKRHeapFUliP7JKRHeap(heap, 0x20U, 0);

    fn_800070A8(arg1->unk64, buf);
    fn_8000604C(arg1->unk64);

    arc = __nw__FUl(0x68U);
    if (arc != NULL) {
        __ct__13JKRMemArchiveFPvUl15JKRMemBreakFlag(arc, buf, 0U, 0);
    }

    fn_80066328(arc);
}
// fn_8000E3C4 (size: 0x2AC)
// fn_8000E670 (size: 0x80)
// fn_8000E6F0 (size: 0x114)
// fn_8000E804 (size: 0x54)
// fn_8000E858 (size: 0x88)
// fn_8000E8E0 (size: 0x21C)
// fn_8000EAFC (size: 0x5C)
StaticData* fn_8000EB58(void){
    return &static_data;
}


void fn_8000EB64(void){
    fn_80005C00();
}


void fn_8000EB84(void){
    lbl_804A0CB8 = 0x3C;
    lbl_804A0CBC = 0;

    fn_80061B4C(0);
    fn_801868B8((s32)0x80000021, NULL);

    lbl_804A0CB4 = 0x708;

    if (lbl_804A0CB0 != 0) {
        lbl_804A0CB0 = 2;
    }

    fn_800060CC(2);

    switch (lbl_804A0BD8) {
        case 1:
            fn_8003A9A8(0);
            break;
        default:
            fn_8003A9A8(1);
            break;
    }

    fn_800060CC(0x1A);
}
// fn_8000EC18 (size: 0x120)
void fn_8000ED38(void){
    fn_8003AA44();
    fn_80007E68();
}


void fn_8000ED5C(void){
    fn_80186E48(0x1E);
    fn_8003AA68();
}
// fn_8000ED84 (size: 0xAC)
// fn_8000EE30 (size: 0xB8)
// fn_8000EEE8 (size: 0x1D4)
void fn_8000F0BC(void) {
    fn_8000CBD8();
    lbl_804A0CC0 = 0;
}
// fn_8000F0E4 (size: 0x2E8)
// __dt__13JKRFileFinderFv (size: 0x4C)
// fn_8000F418 (size: 0x14C)
// fn_8000F564 (size: 0x2B4)
// fn_8000F818 (size: 0xE0)
void fn_8000F8F8(f32* arg0, f32 farg0) {
    if (*arg0 < farg0) {
        *arg0 = farg0;
    }
}


void fn_8000F90C(f32* arg0, f32 farg0) {
    if (*arg0 > farg0) {
        *arg0 = farg0;
    }
}


f32 fn_8000F920(void) {
    return (f32) fn_80009510() / lbl_804A2548;
}


s32 fn_8000F960(UnkObj_8000F960* arg0){
    if ((lbl_804A2558 == arg0->unk0) &&
        (lbl_804A2558 == arg0->unk4) &&
        (lbl_804A2558 == arg0->unk8))
    {
        return 1;
    }
    return 0;
}
// fn_8000F998 (size: 0x164)
void fn_8000FAFC(UnkObj_8000FAFC* arg0, UnkObj_8000FAFC* arg1){
    f32 t;

    arg1->unk0  = arg0->unk0;
    arg1->unk4  = arg0->unk4;
    arg1->unk8  = arg0->unk8;
    arg1->unkC  = arg0->unkC;
    arg1->unk10 = arg0->unk10;
    arg1->unk14 = arg0->unk14;
    arg1->unk18 = arg0->unk18;
    arg1->unk1C = arg0->unk1C;
    arg1->unk20 = arg0->unk20;
    arg1->unk24 = arg0->unk24;
    arg1->unk28 = arg0->unk28;
    arg1->unk2C = arg0->unk2C;

    t = lbl_804A2558;
    arg1->unk30 = t;
    arg1->unk34 = t;
    arg1->unk38 = t;

    arg1->unk3C = lbl_804A2570;
}
// fn_8000FB78 (size: 0x344)
// fn_8000FEBC (size: 0xB4)
// fn_8000FF70 (size: 0x15C)
void fn_800100CC(const UnkMat_800100CC* arg0, const UnkVec3_800100CC* arg1, UnkOut3_800100CC* arg2){
    arg2->unk0 = arg0->unkC  + ((arg0->unk8  * arg1->unk8) + ((arg0->unk0  * arg1->unk0) + (arg0->unk4  * arg1->unk4)));

    arg2->unk4 = arg0->unk1C + ((arg0->unk18 * arg1->unk8) + ((arg0->unk10 * arg1->unk0) + (arg0->unk14 * arg1->unk4)));

    arg2->unk8 = arg0->unk2C + ((arg0->unk28 * arg1->unk8) + ((arg0->unk20 * arg1->unk0) + (arg0->unk24 * arg1->unk4)));
}


void fn_80010178(const UnkMat_80010178* arg0, const UnkVec3_80010178* arg1, UnkOut3_80010178* arg2){
    arg2->unk0 = (arg0->unk8  * arg1->unk8) + ((arg0->unk0  * arg1->unk0) + (arg0->unk4  * arg1->unk4));

    arg2->unk4 = (arg0->unk18 * arg1->unk8) + ((arg0->unk10 * arg1->unk0) + (arg0->unk14 * arg1->unk4));

    arg2->unk8 = (arg0->unk28 * arg1->unk8) + ((arg0->unk20 * arg1->unk0) + (arg0->unk24 * arg1->unk4));
}
// fn_8001020C (size: 0x13C)
// fn_80010348 (size: 0xCC)
s32 fn_80010414(s32* arg0, s32 arg1, s32 arg2){
    s32 r0 = *arg0;

    if (r0 > arg1) {
        s32 v = r0 - arg2;
        *arg0 = v;

        if (*arg0 <= arg1) {
            *arg0 = arg1;
            return 1;
        }
    }
    else {
        s32 v = r0 + arg2;
        *arg0 = v;

        if (*arg0 >= arg1) {
            *arg0 = arg1;
            return 1;
        }
    }

    return 0;
}


s32 fn_80010468(s32 arg0, s32 arg1, s32 arg2){
    if (arg0 > arg1) {
        arg0 -= arg2;
        if (arg0 > arg1) {
            return arg0;
        }
        return arg1;
    }

    arg0 += arg2;
    if (arg0 < arg1) {
        return arg0;
    }
    return arg1;
}
// fn_80010498 (size: 0x48)
// fn_800104E0 (size: 0xBC)
// fn_8001059C (size: 0xF4)
// fn_80010690 (size: 0xEC)
// fn_8001077C (size: 0xD4)
// fn_80010850 (size: 0xD8)
// fn_80010928 (size: 0x78)
// fn_800109A0 (size: 0x78)
// fn_80010A18 (size: 0x7C)
void fn_80010A94(void) {
    fn_80026690();
    fn_8002E62C();
    fn_800123DC();
    fn_8001A354();
    fn_8001F970();
    fn_80012450();
    fn_8002F508();
}


void fn_80010ACC(void) {
    fn_80012674();
    fn_8001A8F4();
    fn_80020110();

    fn_800263D0(0, 0, fn_800286E0, fn_80028C70, 0, 0, 0, lbl_804A25A0, lbl_804A25A4, lbl_804A25A0);

    fn_800263D0(0, 0, fn_80028F48, fn_80028F58, 0, 0, 0, lbl_804A25A0, lbl_804A25A0, lbl_804A25A0);
}


void fn_80010B5C(void) {
    fn_80020040();
}


s32 fn_80010B7C(s16 arg0, s16 arg1){
    if ((u32)lbl_804A0C48 <= 1U) {
        return 0;
    }
    if (arg1 >= 0x1E0) {
        return 0;
    }

    lbl_80498B88 = arg0;
    lbl_804A0CDC = (s16)(arg1 + 0x52);
    lbl_80498B70 = 2;
    lbl_80498B8A = arg1;
    lbl_804A0CDA = (s16)(arg0 + 0x6E);

    if ((s16)lbl_804A0CDC > 0x1E0) {
        lbl_804A0CDC = 0x1E0;
    }

    return 1;
}
// fn_80010BE0 (size: 0x230)
// fn_80010E10 (size: 0x1A8)
// fn_80010FB8 (size: 0x1BC)
// fn_80011174 (size: 0x100)
void fn_80011274(s32 arg0) {
    switch (arg0) {
        case 0:
            fn_80017578();
            fn_80016378();
            return;
        case 1:
            fn_80011174();
            return;
    }
}
// fn_800112B8 (size: 0xD4)
// fn_8001138C (size: 0x84)
void fn_80011410(void){
    volatile s32 spC;
    s32 sp8;

    spC = lbl_804A25B4;
    GXSetZMode(1, 3, 1);

    sp8 = spC;
    GXSetCopyClear(&sp8, 0x00FFFFFF);

    fn_800258B8();
    lbl_804A0CD1 = 0;
}

// fn_80011468 (size: 0x7C)
// fn_800114E4 (size: 0x100)
void fn_800115E4(void){
    s32 sp8;
    s32* pSp8;
    u8*  base;

    fn_8005CE78();

    sp8  = lbl_804A0D3C;
    pSp8 = &sp8;
    base = lbl_80398780;

    fn_80015838((void*)(base + 0x18C), pSp8);

    fn_800269A0();
    fn_80014074();
    fn_8001C558();
    fn_8001594C();
}


void fn_80011630(void) {
    fn_80014128();
}

void fn_80011650(void){
    fn_8001C654();
    fn_80025C5C();
    fn_80028610();
    fn_8001F9C0();
    fn_80026A80();
    fn_800141AC();
    fn_80020538();
    fn_8002E8CC();
    fn_8002F9A4();
}
// fn_80011690 (size: 0x25C)
// fn_800118EC (size: 0xFC)
// fn_800119E8 (size: 0x140)
// fn_80011B28 (size: 0xB8)
// fn_80011BE0 (size: 0xBC)
// fn_80011C9C (size: 0x2E0)
// fn_80011F7C (size: 0x234)
// fn_800121B0 (size: 0x1DC)
// fn_8001238C (size: 0x50)
// fn_800123DC (size: 0x74)
// fn_80012450 (size: 0x224)
void fn_80012674(void) {
    fn_8001275C();
}

s32 fn_80012694(u8 arg0){
    if (arg0 == 0xFF) {
        return 0;
    }
    return lbl_804A0D00->unk8[arg0];
}
// fn_800126BC (size: 0xA0)
// fn_8001275C (size: 0x8C)
// fn_800127E8 (size: 0x114)
// fn_800128FC (size: 0x1AC)
// fn_80012AA8 (size: 0xF8)
// fn_80012BA0 (size: 0x1DC)
// fn_80012D7C (size: 0xD0)
// fn_80012E4C (size: 0x74)
// fn_80012EC0 (size: 0x13C)
// fn_80012FFC (size: 0x6D0)
// fn_800136CC (size: 0x128)
// fn_800137F4 (size: 0x1DC)
// fn_800139D0 (size: 0x104)
// fn_80013AD4 (size: 0x140)
// fn_80013C14 (size: 0x1E4)
// fn_80013DF8 (size: 0x8C)
// fn_80013E84 (size: 0x144)
// fn_80013FC8 (size: 0xAC)
// fn_80014074 (size: 0xB4)
// fn_80014128 (size: 0x84)
// fn_800141AC (size: 0xB0)
