/* autogenerated decompilation stub */
/* source asm: auto_03_800401B8_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_800401B8 (size: 0x30)
// fn_800401E8 (size: 0x238)
// fn_80040420 (size: 0x450)
// fn_80040870 (size: 0x26C)
// fn_80040ADC (size: 0x300)
// fn_80040DDC (size: 0x5E4)
// fn_800413C0 (size: 0x494)
// fn_80041854 (size: 0x38)
// fn_8004188C (size: 0x74)
