/* autogenerated decompilation stub */
/* source asm: auto_03_8016F170_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_8016F170 (size: 0x140)
// fn_8016F2B0 (size: 0x90)
// fn_8016F340 (size: 0xC0)
// fn_8016F400 (size: 0x30)
// fn_8016F430 (size: 0x88)
// fn_8016F4B8 (size: 0x208)
// fn_8016F6C0 (size: 0xB8)
// fn_8016F778 (size: 0x6C)
// fn_8016F7E4 (size: 0x17C)
// fn_8016F960 (size: 0xFC)
// fn_8016FA5C (size: 0x6C)
// fn_8016FAC8 (size: 0x6C)
// fn_8016FB34 (size: 0x78)
// fn_8016FBAC (size: 0xCC)
// fn_8016FC78 (size: 0x120)
// fn_8016FD98 (size: 0x40)
// fn_8016FDD8 (size: 0x70)
// fn_8016FE48 (size: 0xCC)
// fn_8016FF14 (size: 0x78)
