/* autogenerated decompilation stub */
/* source asm: auto_03_8000B7A4_text.s */
#include "auto_03_8000B7A4_text.h"
/* FUNCTIONS TO DECOMPILE */
void fn_8000B7A4(s32* arg0){
    *arg0 = 0;
    OSInitMessageQueue((OSMessageQueue*)((u8*)arg0 + 0x4), (void*)((u8*)arg0 + 0x24), 1);
}


void fn_8000B7DC(void){
    Unk_8007271C* temp_r3;

    fn_80065358(1);
    fn_80065358(3);
    fn_80065358(4);
    fn_80065358(5);
    fn_80065358(6);
    fn_80065358(7);
    fn_80065358(0x11);

    temp_r3 = (Unk_8007271C*)fn_8007271C(0);
    temp_r3->unk16A = (u8)(temp_r3->unk16A | 2);
}


void fn_8000B844(void){
    lbl_804A0C40 = 0;
    fn_80065F18();
    fn_8007271C(0);
    fn_80072374();
    fn_800375BC((void*)lbl_803C2E10);
    lbl_80498B2C = 2;
    fn_80061A2C();
    lbl_804A0C48 = 2;
    fn_8004C69C();
}


s32 fn_8000B8A0(void) {
    if ((s32) lbl_804A0BE0 != 0) {
        return 3;
    }
    return fn_8004C734();
}


void fn_8000B8D4(void){
    fn_8004C784();
    fn_80007EDC();
}


void fn_8000B8F8(void){
    fn_8004C7DC();
}
// fn_8000B918 (size: 0x14C)
// fn_8000BA64 (size: 0x150)
// fn_8000BBB4 (size: 0x138)
// fn_8000BCEC (size: 0x118)
// fn_8000BE04 (size: 0xB8)

void fn_8000BEBC(void){
    fn_800060CC(0x0B);
    fn_800B8424(lbl_804A0C20);
    fn_800615F8();
    fn_800060CC(6);
    fn_800060CC(1);
    fn_80010B5C();
    fn_80010A94();
    fn_800060CC(7);
    fn_8015DD98((void*)lbl_803CD4FC, 0x80, 0x400, 0x400);
    fn_80160BE0();
    fn_800060CC(0x11);
    fn_800B853C();
    fn_8005D44C();
    fn_800060CC(2);
    fn_80037B3C();
}
// fn_8000BF44 (size: 0x110)
// fn_8000C054 (size: 0x148)

void fn_8000C19C(void){
    fn_8005E894();
    fn_8000852C((void*)lbl_80398780);

    GXSetAlphaUpdate(1);
    fn_80057698(1);
    fn_800576A8(1);

    fn_800601EC(0x30);
    fn_800601EC(0x130);

    fn_80011630();
    fn_8011DE7C();
    fn_8005D300();

    fn_80057698(1);
    fn_800576A8(1);

    GXSetDstAlpha(0, 0);

    if ((lbl_804A0C44 != 1) && (lbl_804A0C44 != 2) && (lbl_804A0C44 != 3)) {
        fn_8005E814();
    }
}


void fn_8000C238(s32 arg0, s32 arg1){
    if (lbl_804A0C44 == 0) {
        lbl_804A0C54 = arg1;

        if (lbl_80398A70.unk0 == 0) {
            OSSendMessage((void*)((u8*)&lbl_80398A70 + 4), arg0, 0);
        }
    }
}


s32 fn_8000C284(void) {
    return lbl_804A0C50;
}

// fn_8000C28C (size: 0xDC)
// fn_8000C368 (size: 0xFC)
// fn_8000C464 (size: 0x110)
void fn_8000C574(void){
    if ((lbl_804A0C44 == 2) && (fn_8002981C() != 0)) {
        s32* p;

        lbl_804A0C44 = 0;
        lbl_804A0FB0 = 1;

        fn_80188318(0x1037);
        fn_80188318(0x3804);
        fn_801886F0(0);

        fn_80029E08();
        fn_80120020();
        fn_801868B8((u8)lbl_804A0B88, 0);

        fn_8005CE78();
        fn_80007D38(2);

        p = &lbl_80398A70.unk0;
        lbl_804A0C50 = 0;
        *p = 0;
        fn_8015E07C((void*)lbl_803CD4FC, p);

        if (lbl_804A0B9C != 0) {
            destroy__10JKRExpHeapFv(lbl_804A0B9C);
        }
    }
}
