/* autogenerated decompilation stub */
/* source asm: auto_03_80151410_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_80151410 (size: 0x8)
// fn_80151418 (size: 0x8)
// fn_80151420 (size: 0x8)
// fn_80151428 (size: 0x44)
// fn_8015146C (size: 0x6C)
// fn_801514D8 (size: 0x64)
// fn_8015153C (size: 0x64)
// fn_801515A0 (size: 0x4)
// fn_801515A4 (size: 0x10C)
// fn_801516B0 (size: 0x28)
// fn_801516D8 (size: 0x8)
// fn_801516E0 (size: 0x38)
// fn_80151718 (size: 0xA0)
// fn_801517B8 (size: 0x214)
