/* autogenerated decompilation stub */
/* source asm: auto_03_801D2E8C_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_801D2E8C (size: 0x58)
// fn_801D2EE4 (size: 0x1C)
// fn_801D2F00 (size: 0x40)
// fn_801D2F40 (size: 0x64)
// fn_801D2FA4 (size: 0xA8)
// fn_801D304C (size: 0xB4)
// fn_801D3100 (size: 0x98)
// fn_801D3198 (size: 0x180)
// fn_801D3318 (size: 0x4E4)
// fn_801D37FC (size: 0xC8)
// fn_801D38C4 (size: 0xF4)
// fn_801D39B8 (size: 0x3AC)
// fn_801D3D64 (size: 0x240)
// fn_801D3FA4 (size: 0x88)
// fn_801D402C (size: 0xC4)
// fn_801D40F0 (size: 0xC)
// fn_801D40FC (size: 0x28)
// fn_801D4124 (size: 0x10)
// fn_801D4134 (size: 0x68)
// __dt__14JUTDirectPrintFv (size: 0x6C)
