/* autogenerated decompilation stub */
/* source asm: auto_03_80107F08_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_80107F08 (size: 0x8)
// fn_80107F10 (size: 0x8)
// fn_80107F18 (size: 0x8)
// fn_80107F20 (size: 0x44)
// fn_80107F64 (size: 0xB8)
// fn_8010801C (size: 0x8C)
// fn_801080A8 (size: 0x3C)
// fn_801080E4 (size: 0x8)
// fn_801080EC (size: 0xFC)
// fn_801081E8 (size: 0x16C)
// fn_80108354 (size: 0x2B4)
