/* autogenerated decompilation stub */
/* source asm: auto_03_80009418_text.s */
#include "auto_03_80009418_text.h"
/* FUNCTIONS TO DECOMPILE */
void fn_80009418(s32 arg0) {
    fn_801D2CD4(lbl_804A0BF8, 0x0F0F000F, 0x20 / arg0, 4 / arg0);
}


void fn_80009458(void) {}

// fn_8000945C (size: 0xA8)
void fn_80009504(void) {
    lbl_80498AF8 = 1;
}


s32 fn_80009510(void) {
    lbl_80498AF8 = (lbl_80498AF8 * 0x19660D) + 0x3C6EF35F;
    return lbl_80498AF8;
}

// fn_80009534 (size: 0x308)
// fn_8000983C (size: 0xBC)
// fn_800098F8 (size: 0x160)
// fn_80009A58 (size: 0x550)
// fn_80009FA8 (size: 0x1DC)
// fn_8000A184 (size: 0x4C)
void fn_8000A1D0(void* arg0) {
    MyStructFlt* s = (MyStructFlt*)arg0;
    f32 val = lbl_804A2478;

    s->unkC = val;
    s->unk8 = val;
    s->unk4 = val;
    s->unk0 = val;

    s->unk1C = val;
    s->unk18 = val;
    s->unk14 = val;
    s->unk10 = val;

    s->unk2C = val;
    s->unk28 = val;
    s->unk24 = val;
    s->unk20 = val;
}

// fn_8000A208 (size: 0xDC)
// fn_8000A2E4 (size: 0x120)
// fn_8000A404 (size: 0x71C)
// fn_8000AB20 (size: 0x100)
void fn_8000AC20(void) {
    lbl_803989E0.unk10 = 0;
    lbl_803989E0.unkC = 0x200;
    lbl_803989E0.unk0 = fn_80005F94(0x400, 0x20);
    lbl_803989E0.unk4 = (s32)(lbl_803989E0.unk0 + 0x200);
}


void fn_8000AC78(void) {
    fn_8000604C(lbl_803989E0.unk0);
}


void fn_8000ACA4(void){
    s32* w = (s32*)&lbl_803989E0;

    w[4] ^= 1;
    w[2] = w[3] + w[w[4]];
}


s32 fn_8000ACD4(void) {
    return lbl_80498B10;
}


void fn_8000ACDC(s32 arg0) {
    lbl_80498B10 = arg0;
}
// fn_8000ACE4 (size: 0xCC)
void fn_8000ADB0(UnkObj_8000ADB0* arg0, s32 arg1){
    arg0->unk10 = 0;
    arg0->unk14 = 0;
    arg0->unkC  = arg1;
    arg0->unk4  = 0;
    arg0->unk0  = 0;
    arg0->unk8  = 0;
}
// fn_8000ADD0 (size: 0xB0)
