/* autogenerated decompilation stub */
/* source asm: auto_03_8018331C_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_8018331C (size: 0xB8)
// fn_801833D4 (size: 0x5C)
// fn_80183430 (size: 0x18)
// fn_80183448 (size: 0x90)
// fn_801834D8 (size: 0x90)
// fn_80183568 (size: 0xD4)
// fn_8018363C (size: 0x178)
// fn_801837B4 (size: 0xD8)
// fn_8018388C (size: 0x1FC)
// fn_80183A88 (size: 0x30)
// fn_80183AB8 (size: 0x8)
