/* autogenerated decompilation stub */
/* source asm: auto_03_8006E73C_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_8006E73C (size: 0x8)
// fn_8006E744 (size: 0x8)
// fn_8006E74C (size: 0xAC)
// fn_8006E7F8 (size: 0xE0)
// fn_8006E8D8 (size: 0x64)
// fn_8006E93C (size: 0x9C)
// fn_8006E9D8 (size: 0x8)
// fn_8006E9E0 (size: 0x50)
// fn_8006EA30 (size: 0x5C)
// fn_8006EA8C (size: 0x148)
// fn_8006EBD4 (size: 0x138)
// fn_8006ED0C (size: 0x80)
// fn_8006ED8C (size: 0x44)
// fn_8006EDD0 (size: 0xB4)
// fn_8006EE84 (size: 0x64)
// fn_8006EEE8 (size: 0x174)
