/* autogenerated decompilation stub */
/* source asm: auto_03_8012C1C4_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_8012C1C4 (size: 0x18)
// fn_8012C1DC (size: 0xB4)
// fn_8012C290 (size: 0xC4)
// fn_8012C354 (size: 0x98)
// fn_8012C3EC (size: 0x64)
// fn_8012C450 (size: 0x48)
// fn_8012C498 (size: 0x8)
// fn_8012C4A0 (size: 0x14C)
// fn_8012C5EC (size: 0x1B0)
// fn_8012C79C (size: 0x7C)
// fn_8012C818 (size: 0x78)
// fn_8012C890 (size: 0x4C)
// fn_8012C8DC (size: 0x34)
// fn_8012C910 (size: 0x50)
