/* autogenerated decompilation stub */
/* source asm: auto_03_801591FC_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_801591FC (size: 0x8)
// fn_80159204 (size: 0x8)
// fn_8015920C (size: 0x8)
// fn_80159214 (size: 0x64)
// fn_80159278 (size: 0x74)
// fn_801592EC (size: 0x8C)
// fn_80159378 (size: 0x8C)
// fn_80159404 (size: 0x70)
// fn_80159474 (size: 0x160)
// fn_801595D4 (size: 0xEC)
// fn_801596C0 (size: 0x3F4)
// fn_80159AB4 (size: 0x24)
