/* autogenerated decompilation stub */
/* source asm: auto_03_800FE6E0_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_800FE6E0 (size: 0x114)
// fn_800FE7F4 (size: 0x64)
// fn_800FE858 (size: 0x64)
// fn_800FE8BC (size: 0x3E4)
// fn_800FECA0 (size: 0x8)
// fn_800FECA8 (size: 0x10)
// fn_800FECB8 (size: 0x274)
// fn_800FEF2C (size: 0x38)
// fn_800FEF64 (size: 0x1BC)
// fn_800FF120 (size: 0xE4)
// fn_800FF204 (size: 0x1E8)
// fn_800FF3EC (size: 0x8)
// fn_800FF3F4 (size: 0x8)
// fn_800FF3FC (size: 0x8)
// fn_800FF404 (size: 0x8)
// fn_800FF40C (size: 0x8)
// fn_800FF414 (size: 0x8)
// fn_800FF41C (size: 0x4C)
// fn_800FF468 (size: 0x84)
