/* autogenerated decompilation stub */
/* source asm: auto_03_800A85F4_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_800A85F4 (size: 0x8)
// fn_800A85FC (size: 0x9C)
// fn_800A8698 (size: 0x64)
// fn_800A86FC (size: 0x64)
// fn_800A8760 (size: 0x14C)
// fn_800A88AC (size: 0x8)
// fn_800A88B4 (size: 0x28)
// fn_800A88DC (size: 0x8)
// fn_800A88E4 (size: 0x98)
// fn_800A897C (size: 0xB8)
