/* autogenerated decompilation stub */
/* source asm: auto_03_80070668_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_80070668 (size: 0x8)
// fn_80070670 (size: 0x8)
// fn_80070678 (size: 0x8)
// fn_80070680 (size: 0x8)
// fn_80070688 (size: 0x8)
// fn_80070690 (size: 0x8)
// fn_80070698 (size: 0x4)
// fn_8007069C (size: 0xDC)
// fn_80070778 (size: 0xA4)
// fn_8007081C (size: 0x64)
// fn_80070880 (size: 0xB0)
// fn_80070930 (size: 0x8)
// fn_80070938 (size: 0x8)
// fn_80070940 (size: 0x70)
// fn_800709B0 (size: 0x14C)
