/* autogenerated decompilation stub */
/* source asm: auto_03_801CC244_text.s */

/* FUNCTIONS TO DECOMPILE */
// __ct__11JKRAramHeapFUlUl (size: 0xE4)
// __dt__11JKRAramHeapFv (size: 0xA8)
// alloc__11JKRAramHeapFUlQ211JKRAramHeap10EAllocMode (size: 0x80)
// allocFromHead__11JKRAramHeapFUl (size: 0x8C)
// allocFromTail__11JKRAramHeapFUl (size: 0x78)
