/* autogenerated decompilation stub */
/* source asm: auto_03_800F60E8_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_800F60E8 (size: 0x114)
// fn_800F61FC (size: 0x64)
// fn_800F6260 (size: 0x64)
// fn_800F62C4 (size: 0x8)
// fn_800F62CC (size: 0x54)
// fn_800F6320 (size: 0xB0)
// fn_800F63D0 (size: 0x30)
// fn_800F6400 (size: 0x68)
// fn_800F6468 (size: 0x58)
// fn_800F64C0 (size: 0x88)
// fn_800F6548 (size: 0x8)
// fn_800F6550 (size: 0x68)
// fn_800F65B8 (size: 0x28)
// fn_800F65E0 (size: 0x3C)
// fn_800F661C (size: 0x6C)
