/* autogenerated decompilation stub */
/* source asm: auto_03_80043C64_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_80043C64 (size: 0xA8)
// fn_80043D0C (size: 0x94)
// fn_80043DA0 (size: 0x34)
// fn_80043DD4 (size: 0x44)
