/* autogenerated decompilation stub */
/* source asm: auto_03_800082F0_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_800082F0 (size: 0x124)
// fn_80008414 (size: 0x50)
// fn_80008464 (size: 0x4C)
// fn_800084B0 (size: 0x7C)
// fn_8000852C (size: 0x17C)
// fn_800086A8 (size: 0x158)
// fn_80008800 (size: 0xB4)
// fn_800088B4 (size: 0xCC)
// fn_80008980 (size: 0x2B0)
// fn_80008C30 (size: 0x3F0)
// fn_80009020 (size: 0x2A4)
// fn_800092C4 (size: 0xA4)
// fn_80009368 (size: 0x64)
