/* autogenerated decompilation stub */
/* source asm: auto_03_80134954_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_80134954 (size: 0x110)
// fn_80134A64 (size: 0x4C)
// fn_80134AB0 (size: 0x74)
// fn_80134B24 (size: 0xF0)
// fn_80134C14 (size: 0x7C)
// fn_80134C90 (size: 0x17C)
// fn_80134E0C (size: 0x8C)
// fn_80134E98 (size: 0xB0)
// fn_80134F48 (size: 0x8)
// fn_80134F50 (size: 0xB0)
// fn_80135000 (size: 0x214)
// fn_80135214 (size: 0x48)
// fn_8013525C (size: 0x8C)
// fn_801352E8 (size: 0x118)
// fn_80135400 (size: 0x2C)
// fn_8013542C (size: 0x17C)
// fn_801355A8 (size: 0x88)
