/* autogenerated decompilation stub */
/* source asm: auto_03_800F57EC_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_800F57EC (size: 0x8)
// fn_800F57F4 (size: 0x8)
// fn_800F57FC (size: 0x8)
// fn_800F5804 (size: 0x8)
// fn_800F580C (size: 0xF4)
// fn_800F5900 (size: 0x64)
// fn_800F5964 (size: 0x64)
// fn_800F59C8 (size: 0x8)
// fn_800F59D0 (size: 0x5C)
// fn_800F5A2C (size: 0xB0)
// fn_800F5ADC (size: 0x6C)
// fn_800F5B48 (size: 0x68)
// fn_800F5BB0 (size: 0x64)
// fn_800F5C14 (size: 0xE8)
// fn_800F5CFC (size: 0x58)
// fn_800F5D54 (size: 0x88)
// fn_800F5DDC (size: 0x8)
// fn_800F5DE4 (size: 0x68)
// fn_800F5E4C (size: 0x13C)
// fn_800F5F88 (size: 0x64)
