/* autogenerated decompilation stub */
/* source asm: auto_03_8006E008_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_8006E008 (size: 0x8)
// fn_8006E010 (size: 0xAC)
// fn_8006E0BC (size: 0xF8)
// fn_8006E1B4 (size: 0x64)
// fn_8006E218 (size: 0x120)
// fn_8006E338 (size: 0x14)
// fn_8006E34C (size: 0x8)
// fn_8006E354 (size: 0x8)
// fn_8006E35C (size: 0x128)
// fn_8006E484 (size: 0x78)
// fn_8006E4FC (size: 0x8)
// fn_8006E504 (size: 0x94)
// fn_8006E598 (size: 0x138)
