/* autogenerated decompilation stub */
/* source asm: auto_03_800FA4B8_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_800FA4B8 (size: 0x8)
// fn_800FA4C0 (size: 0x8)
// fn_800FA4C8 (size: 0x8)
// fn_800FA4D0 (size: 0x8)
// fn_800FA4D8 (size: 0x54)
// fn_800FA52C (size: 0xC8)
// fn_800FA5F4 (size: 0x8C)
// fn_800FA680 (size: 0x8C)
// fn_800FA70C (size: 0x8)
// fn_800FA714 (size: 0x2A8)
// fn_800FA9BC (size: 0xA8)
// fn_800FAA64 (size: 0xBC)
// fn_800FAB20 (size: 0x1CC)
// fn_800FACEC (size: 0xDC)
// fn_800FADC8 (size: 0x11C)
// fn_800FAEE4 (size: 0x38)
// fn_800FAF1C (size: 0x38)
// fn_800FAF54 (size: 0x54)
// fn_800FAFA8 (size: 0x38C)
