/* autogenerated decompilation stub */
/* source asm: auto_03_800D380C_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_800D380C (size: 0x8C)
// fn_800D3898 (size: 0x90)
// fn_800D3928 (size: 0x4)
// fn_800D392C (size: 0x5C)
// fn_800D3988 (size: 0xA0)
// fn_800D3A28 (size: 0x8)
// fn_800D3A30 (size: 0x4C)
// fn_800D3A7C (size: 0xA8)
// fn_800D3B24 (size: 0x8C)
// fn_800D3BB0 (size: 0x4C)
// fn_800D3BFC (size: 0x38)
// fn_800D3C34 (size: 0x48)
// fn_800D3C7C (size: 0x50)
// fn_800D3CCC (size: 0x8)
// fn_800D3CD4 (size: 0xC4)
// fn_800D3D98 (size: 0x84)
// fn_800D3E1C (size: 0x2B4)
