/* autogenerated decompilation stub */
/* source asm: auto_03_80153B50_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_80153B50 (size: 0x54)
// fn_80153BA4 (size: 0xA0)
// fn_80153C44 (size: 0x7C)
// fn_80153CC0 (size: 0x7C)
// fn_80153D3C (size: 0xD4)
// fn_80153E10 (size: 0x40)
// fn_80153E50 (size: 0x60)
// fn_80153EB0 (size: 0x5D8)
// fn_80154488 (size: 0xFC)
// fn_80154584 (size: 0x54)
// fn_801545D8 (size: 0x48)
// fn_80154620 (size: 0xEC)
// fn_8015470C (size: 0x1E0)
// fn_801548EC (size: 0x17C)
// fn_80154A68 (size: 0x8)
// fn_80154A70 (size: 0x3C)
// fn_80154AAC (size: 0x40)
// fn_80154AEC (size: 0x210)
