/* autogenerated decompilation stub */
/* source asm: auto_03_8010F480_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_8010F480 (size: 0x8)
// fn_8010F488 (size: 0x8)
// fn_8010F490 (size: 0x8)
// fn_8010F498 (size: 0x8)
// fn_8010F4A0 (size: 0x8)
// fn_8010F4A8 (size: 0x8)
// fn_8010F4B0 (size: 0x44)
// fn_8010F4F4 (size: 0x6C)
// fn_8010F560 (size: 0x64)
// fn_8010F5C4 (size: 0x64)
// fn_8010F628 (size: 0x4)
// fn_8010F62C (size: 0x74)
// fn_8010F6A0 (size: 0x8)
// fn_8010F6A8 (size: 0x8)
// fn_8010F6B0 (size: 0x4C)
// fn_8010F6FC (size: 0x60)
// fn_8010F75C (size: 0x384)
// fn_8010FAE0 (size: 0xB4)
