/* autogenerated decompilation stub */
/* source asm: auto_03_801502B0_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_801502B0 (size: 0x74)
// fn_80150324 (size: 0x74)
// fn_80150398 (size: 0x10)
// fn_801503A8 (size: 0x4C)
// fn_801503F4 (size: 0x98)
// fn_8015048C (size: 0xA0)
// fn_8015052C (size: 0x1BC)
// fn_801506E8 (size: 0x50)
// fn_80150738 (size: 0xB4)
// fn_801507EC (size: 0x130)
// fn_8015091C (size: 0x190)
// fn_80150AAC (size: 0x4C)
