/* autogenerated decompilation stub */
/* source asm: auto_03_8000AEEC_text.s */
#include "auto_03_8000AEEC_text.h"
/* FUNCTIONS TO DECOMPILE */
// fn_8000AEEC (size: 0x214)
// fn_8000B100 (size: 0x100)
u16 fn_8000B200(void){
    return lbl_80498B18->unk10;
}


void fn_8000B20C(s32 arg0){
    lbl_804A0C08 = 1;
    OSSendMessage((void*)((u8*)&lbl_80398A40 + 8), arg0, 0);
}
// fn_8000B248 (size: 0x130)
// fn_8000B378 (size: 0x170)
// fn_8000B4E8 (size: 0x1D8)
void fn_8000B6C0(void){
    void** temp_r4;

    fn_80006EF0();

    loop_1:
    lbl_804A0C1C = 0;
    lbl_804A0C18 = 0;
    fn_80009504();
    fn_800060CC(0x0C);
    fn_8000AC20();
    fn_800060CC(0x1A);

    fn_80006F18(lbl_80498B18->unk14);
    fn_8000828C(0x1E);
    fn_8000B4E8();

    lbl_80498B18->unk20(lbl_80498B18);

    fn_8000AC78();

    temp_r4 = &lbl_80212E00[lbl_804A0C20];
    lbl_80498B18 = (Unk_80498B18*)(*temp_r4);

    fn_80006070(0x1A, temp_r4);
    goto loop_1;
}
