/* autogenerated decompilation stub */
/* source asm: auto_03_800D7168_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_800D7168 (size: 0x64)
// fn_800D71CC (size: 0xC4)
// fn_800D7290 (size: 0x8C)
// fn_800D731C (size: 0x8)
// fn_800D7324 (size: 0x48)
// fn_800D736C (size: 0xD0)
