/* autogenerated decompilation stub */
/* source asm: auto_03_800F8E68_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_800F8E68 (size: 0xB4)
// fn_800F8F1C (size: 0x8C)
// fn_800F8FA8 (size: 0x8)
// fn_800F8FB0 (size: 0x24)
// fn_800F8FD4 (size: 0xAC)
// fn_800F9080 (size: 0x8)
// fn_800F9088 (size: 0x24)
// fn_800F90AC (size: 0x24)
// fn_800F90D0 (size: 0x24)
// fn_800F90F4 (size: 0x28)
// fn_800F911C (size: 0x14)
// fn_800F9130 (size: 0x3C)
// fn_800F916C (size: 0x84)
