/* autogenerated decompilation stub */
/* source asm: auto_03_80150B1C_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_80150B1C (size: 0x54)
// fn_80150B70 (size: 0xA0)
// fn_80150C10 (size: 0x8C)
// fn_80150C9C (size: 0x7C)
// fn_80150D18 (size: 0x1C)
// fn_80150D34 (size: 0x8)
// fn_80150D3C (size: 0x8)
// fn_80150D44 (size: 0x8)
// fn_80150D4C (size: 0x48)
// fn_80150D94 (size: 0x38)
// fn_80150DCC (size: 0xC8)
// fn_80150E94 (size: 0x78)
// fn_80150F0C (size: 0x184)
// fn_80151090 (size: 0x8)
// fn_80151098 (size: 0x6C)
// fn_80151104 (size: 0x34)
// fn_80151138 (size: 0x2C)
// fn_80151164 (size: 0x7C)
// fn_801511E0 (size: 0x88)
// fn_80151268 (size: 0xAC)
