/* autogenerated decompilation stub */
/* source asm: auto_03_8015DD7C_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_8015DD7C (size: 0x1C)
// fn_8015DD98 (size: 0x294)
// fn_8015E02C (size: 0x38)
// fn_8015E064 (size: 0x18)
// fn_8015E07C (size: 0x11C)
// fn_8015E198 (size: 0x1C8)
// fn_8015E360 (size: 0xD4)
// fn_8015E434 (size: 0x3C4)
// fn_8015E7F8 (size: 0x1E4)
// fn_8015E9DC (size: 0x68)
// fn_8015EA44 (size: 0x68)
// fn_8015EAAC (size: 0xD4)
// fn_8015EB80 (size: 0xF4)
