/* autogenerated decompilation stub */
/* source asm: auto_03_801CC600_text.s */

/* FUNCTIONS TO DECOMPILE */
// __ct__12JKRAramBlockFUlUlUlUcb (size: 0x6C)
// __dt__12JKRAramBlockFv (size: 0xBC)
// allocHead__12JKRAramBlockFUlUcP11JKRAramHeap (size: 0x9C)
// allocTail__12JKRAramBlockFUlUcP11JKRAramHeap (size: 0xA4)
// prepareCommand__12JKRAramPieceFiUlUlUlP12JKRAramBlockPFUl_v (size: 0x6C)
// sendCommand__12JKRAramPieceFP12JKRAMCommand (size: 0x20)
// orderAsync__12JKRAramPieceFiUlUlUlP12JKRAramBlockPFUl_v (size: 0xD4)
// sync__12JKRAramPieceFP12JKRAMCommandi (size: 0xC0)
// orderSync__12JKRAramPieceFiUlUlUlP12JKRAramBlock (size: 0x11C)
// startDMA__12JKRAramPieceFP12JKRAMCommand (size: 0x78)
// doneDMA__12JKRAramPieceFUl (size: 0xA8)
// __ct__12JKRAMCommandFv (size: 0x74)
// __dt__12JKRAMCommandFv (size: 0xA8)
