/* autogenerated decompilation stub */
/* source asm: auto_03_80045724_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_80045724 (size: 0x30)
// fn_80045754 (size: 0x54)
// fn_800457A8 (size: 0x114)
// fn_800458BC (size: 0x1C8)
// fn_80045A84 (size: 0x3F0)
// fn_80045E74 (size: 0x90)
