/* autogenerated decompilation stub */
/* source asm: auto_03_801576D0_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_801576D0 (size: 0x8)
// fn_801576D8 (size: 0x8)
// fn_801576E0 (size: 0x8)
// fn_801576E8 (size: 0x64)
// fn_8015774C (size: 0x74)
// fn_801577C0 (size: 0x7C)
// fn_8015783C (size: 0x7C)
// fn_801578B8 (size: 0x12C)
// fn_801579E4 (size: 0x154)
// fn_80157B38 (size: 0xC0)
// fn_80157BF8 (size: 0x324)
