/* autogenerated decompilation stub */
/* source asm: auto_03_8010AA88_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_8010AA88 (size: 0x8)
// fn_8010AA90 (size: 0x8)
// fn_8010AA98 (size: 0x8)
// fn_8010AAA0 (size: 0x8)
// fn_8010AAA8 (size: 0x54)
// fn_8010AAFC (size: 0xA8)
// fn_8010ABA4 (size: 0x8C)
// fn_8010AC30 (size: 0x17C)
// fn_8010ADAC (size: 0x6C)
// fn_8010AE18 (size: 0xC)
// fn_8010AE24 (size: 0x40)
// fn_8010AE64 (size: 0xC)
// fn_8010AE70 (size: 0xB0)
