/* autogenerated decompilation stub */
/* source asm: auto_03_8000AEEC_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_8000AEEC (size: 0x214)
// fn_8000B100 (size: 0x100)
// fn_8000B200 (size: 0xC)
// fn_8000B20C (size: 0x3C)
// fn_8000B248 (size: 0x130)
// fn_8000B378 (size: 0x170)
// fn_8000B4E8 (size: 0x1D8)
// fn_8000B6C0 (size: 0x8C)
