/* autogenerated decompilation stub */
/* source asm: auto_03_800082F0_text.s */
#include "auto_03_800082F0_text.h"
/* FUNCTIONS TO DECOMPILE */
// fn_800082F0 (size: 0x124)
void fn_80008414(s32 arg0) {
    fn_800088B4();
    MTXLookAt((void*)(arg0 + 0x18C), (void*)arg0, (void*)(arg0 + 0x48), (void*)(arg0 + 0x0C));
    fn_801B1F3C((void*)(arg0 + 0x18C), (void*)lbl_80492040);
}


void fn_80008464(s32 arg0){
    MTXLookAt((void*)(arg0 + 0x18C), (void*)(arg0 + 0x24), (void*)(arg0 + 0x18), (void*)(arg0 + 0x30));

    fn_801B1F3C((void*)(arg0 + 0x18C), (void*)lbl_80492040);
}


void fn_800084B0(void* arg0){
    volatile u8* v = (volatile u8*)arg0;

    MTXOrtho((void*)(v + 0x14C), lbl_804A23D0, lbl_804A23D4, lbl_804A23D8, lbl_804A23DC, *(volatile f32*)(v + 0x98), *(volatile f32*)(v + 0x9C));
    GXSetProjection((void*)(v + 0x14C), 1);
    MTXLightOrtho((void*)(v + 0x1BC), lbl_804A23D4, lbl_804A23D0, lbl_804A23D8, lbl_804A23DC, lbl_804A23E0, lbl_804A23E0, lbl_804A23E0, lbl_804A23E0);
}
// fn_8000852C (size: 0x17C)
// fn_800086A8 (size: 0x158)
void fn_80008800(void* arg0, f32 farg0, f32 farg1, f32 farg2, f32 farg3){
    u8* base = (u8*)arg0;

    MTXFrustum((void*)(base + 0x14C), farg0, farg1, farg2, farg3, *(f32*)(base + 0x98), *(f32*)(base + 0x9C));
    GXSetProjection((void*)(base + 0x14C), 0);
    MTXLightPerspective((void*)(base + 0x1BC), *(f32*)(base + 0x90), *(f32*)(base + 0x94), lbl_804A23E0, lbl_804A23E0, lbl_804A23E0, lbl_804A23E0);
    fn_80008C30(arg0, farg0, farg1, farg2, farg3, *(f32*)(base + 0x98), *(f32*)(base + 0x9C));
}
// fn_800088B4 (size: 0xCC)
// fn_80008980 (size: 0x2B0)
// fn_80008C30 (size: 0x3F0)
// fn_80009020 (size: 0x2A4)
s32 fn_800092C4(s32 arg0){
    u8* base = (u8*)arg0;

    Vec3f v18;
    Vec3f v0C;

    PSVECSubtract((const Vec3f*)(base + 0x0C), (const Vec3f*)(base + 0x00), &v18);
    PSVECNormalize(&v18, &v18);

    PSVECSubtract((const Vec3f*)(base + 0x30), (const Vec3f*)(base + 0x24), &v0C);
    PSVECNormalize(&v0C, &v0C);

    if ((v18.x * v0C.x + v18.y * v0C.y + v18.z * v0C.z) < lbl_804A2420) {
        return 1;
    }
    return 0;
}
// fn_80009368 (size: 0x64)
