/* autogenerated decompilation stub */
/* source asm: auto_03_80158B68_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_80158B68 (size: 0x8)
// fn_80158B70 (size: 0x8)
// fn_80158B78 (size: 0x8)
// fn_80158B80 (size: 0x8)
// fn_80158B88 (size: 0x4C)
// fn_80158BD4 (size: 0x74)
// fn_80158C48 (size: 0x8C)
// fn_80158CD4 (size: 0x8C)
// fn_80158D60 (size: 0x64)
// fn_80158DC4 (size: 0x128)
// fn_80158EEC (size: 0x140)
// fn_8015902C (size: 0x164)
