/* autogenerated decompilation stub */
/* source asm: auto_03_8016CF7C_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_8016CF7C (size: 0x5C)
// fn_8016CFD8 (size: 0x4)
// fn_8016CFDC (size: 0x4)
// fn_8016CFE0 (size: 0x4)
// fn_8016CFE4 (size: 0x4)
// fn_8016CFE8 (size: 0x4)
// fn_8016CFEC (size: 0x4)
// fn_8016CFF0 (size: 0x4)
// fn_8016CFF4 (size: 0x4)
// fn_8016CFF8 (size: 0x84)
// fn_8016D07C (size: 0x188)
// fn_8016D204 (size: 0x1D4)
// fn_8016D3D8 (size: 0x200)
// fn_8016D5D8 (size: 0x2C)
