/* autogenerated decompilation stub */
/* source asm: auto_03_80046DE4_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_80046DE4 (size: 0x290)
// fn_80047074 (size: 0x40)
// fn_800470B4 (size: 0x10)
// fn_800470C4 (size: 0x260)
// fn_80047324 (size: 0x16D8)
// fn_800489FC (size: 0x264)
// fn_80048C60 (size: 0xFC)
// fn_80048D5C (size: 0x184)
// fn_80048EE0 (size: 0x94)
// fn_80048F74 (size: 0x11C)
// fn_80049090 (size: 0x7EC)
// fn_8004987C (size: 0x2B78)
// fn_8004C3F4 (size: 0x1A8)
// fn_8004C59C (size: 0x100)
// fn_8004C69C (size: 0x98)
// fn_8004C734 (size: 0x50)
// fn_8004C784 (size: 0x58)
// fn_8004C7DC (size: 0x5C)
// fn_8004C838 (size: 0x8)
