/* autogenerated decompilation stub */
/* source asm: auto_03_800D62C0_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_800D62C0 (size: 0x8)
// fn_800D62C8 (size: 0x8)
// fn_800D62D0 (size: 0x8)
// fn_800D62D8 (size: 0x8)
// fn_800D62E0 (size: 0x78)
// fn_800D6358 (size: 0x64)
// fn_800D63BC (size: 0x20)
// fn_800D63DC (size: 0x28)
// fn_800D6404 (size: 0x34)
// fn_800D6438 (size: 0x450)
// fn_800D6888 (size: 0x8)
// fn_800D6890 (size: 0x228)
// fn_800D6AB8 (size: 0x8)
// fn_800D6AC0 (size: 0x14C)
// fn_800D6C0C (size: 0x34)
// fn_800D6C40 (size: 0x3EC)
// fn_800D702C (size: 0x70)
