/* autogenerated decompilation stub */
/* source asm: auto_03_80046214_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_80046214 (size: 0x54)
// fn_80046268 (size: 0x68)
// fn_800462D0 (size: 0x208)
// fn_800464D8 (size: 0x24C)
// fn_80046724 (size: 0x5FC)
// fn_80046D20 (size: 0x4)
// fn_80046D24 (size: 0x4C)
// fn_80046D70 (size: 0x2C)
