/* autogenerated decompilation stub */
/* source asm: auto_03_80005C00_text.s */

#include "auto_03_80005C00_text.h"


/* FUNCTIONS TO DECOMPILE */
void fn_80005C00(void){
    lbl_804A0B70 = 0;
    fn_80005C8C(lbl_8038F860);
}
// fn_80005C30 (size: 0x5C)
// fn_80005C8C (size: 0x6C)
// fn_80005CF8 (size: 0x10C)
// fn_80005E04 (size: 0xB4)
// fn_80005EB8 (size: 0x58)
// fn_80005F10 (size: 0x84)
// fn_80005F94 (size: 0xB8)
void fn_8000604C(JKRHeap* arg0, void* unused, JKRHeap* arg2) {
    (void)unused;
    free__7JKRHeapFPvP7JKRHeap(arg0, NULL, arg2);
}
// fn_80006070 (size: 0x5C)
void fn_800060CC(u8 arg0) {
    lbl_80498AE8 = arg0;
    changeGroupID__10JKRExpHeapFUc(lbl_804A0B94, arg0);
    changeGroupID__10JKRExpHeapFUc(lbl_804A0B98, arg0);
}


u8 fn_80006110(void) {
    return lbl_80498AE8;
}


void fn_80006118(void) {
    becomeCurrentHeap__7JKRHeapFv(lbl_804A0B98);
}


void fn_8000613C(void) {
    fn_80005F94();
}


u8* fn_8000615C(void) {
    return &lbl_8038FB98[0];
}
// fn_80006168 (size: 0x128)
// fn_80006290 (size: 0x98)
// fn_80006328 (size: 0x9C)
// fn_800063C4 (size: 0xBC)
// fn_80006480 (size: 0x90)
// fn_80006510 (size: 0xAC)
// fn_800065BC (size: 0xEC)
// fn_800066A8 (size: 0x160)
// fn_80006808 (size: 0x58)
// fn_80006860 (size: 0xAC)
// fn_8000690C (size: 0x130)
Unk_8001F020_Obj* fn_80006A3C(s32 arg0){
    return *(Unk_8001F020_Obj**)((u8*)arg0 + 0x70);
}

s32 fn_80006A44(void* arg0){
    return *(s32*)((u8*)arg0 + 0x64);
}


s32 fn_80006A4C(void* arg0){
    return *(s32*)((u8*)arg0 + 0x34);
}


s32 fn_80006A54(void* arg0){
    return *(s32*)((u8*)arg0 + 0x6C);
}


u8 fn_80006A5C(void){
    return (u8)!!lbl_80391D98[0];
}


s32 fn_80006A78(void) {
    return ((Obj_80391D98*)lbl_80391D98)->unk4;
}


void fn_80006A88(void) {
    fn_80006168((void*)&lbl_80391D98);
}
// fn_80006AB0 (size: 0xAC)
// fn_80006B5C (size: 0xA4)
void fn_80006C00(void* unused, Arg_80006C00* a) {
    u32* r5 = a->unk64;
    u32 r3  = *r5;

    if ((u32)(r3 + 0xADBF0000u) != 0x5243u) {
        lbl_804A0BA8 = 1;
        return;
    }

    if (a->unk6C != 0) {
        __ct__13JKRMemArchiveFPvUl15JKRMemBreakFlag(a->unk6C, (void*)r5, 0u, (JKRMemBreakFlag)a->unk84);
    }

    (void)unused;
}


void fn_80006C58(void* buf, Obj_80006C58* size){
    s32 unused1;
    s32* temp_r4;
    (void)buf;

    fn_80006B5C();

    if (lbl_804A0BA8 == 0) {
        temp_r4 = size->unk68;

        if ((u32)(temp_r4[0] + 0xADBF0000u) != 0x5243u) {
            lbl_804A0BA8 = 1;
        }
        else {
            if (size->unk6C != 0) {
                __ct__13JKRMemArchiveFPvUl15JKRMemBreakFlag(size->unk6C, (void*)temp_r4, 0, (JKRMemBreakFlag)size->unk84);
            }
        }
    }
}


void fn_80006CC8(void){
    fn_80006E7C(&lbl_80393DC0);
}


void fn_80006CF0(s32 arg0){
    OSSendMessage((void*)((u8*)&lbl_80393DC0 + 0x310), arg0, 1);
}

// fn_80006D24 (size: 0x158)
// fn_80006E7C (size: 0x74)
void fn_80006EF0(void) {
    fn_8000701C(&lbl_80398200);
}


void fn_80006F18(s32 arg0){
    lbl_80394200.unk4358 = arg0;

    OSReceiveMessage((u8*)&lbl_80394200 + 0x4334, 0, 0);
    OSSendMessage   ((u8*)&lbl_80394200 + 0x4310, 0, 0);
}


void fn_80006F68(void){
    OSReceiveMessage((void*)((u8*)&lbl_80398200 + 0x334), 0, 0);
}
// fn_80006F9C (size: 0x80)
// fn_8000701C (size: 0x7C)
s32 fn_80007098(void* arg0){
    Obj_80007098* obj = (Obj_80007098*)arg0;
    return (s32)((obj->unk4 + 0x1F) & 0xFFFFFFE0);
}
// fn_800070A8 (size: 0x1C8)
// fn_80007270 (size: 0x208)
void fn_80007478(s32 arg0) {
    Global_80398560* p = &lbl_80398560;
    if ((u32)(arg0 - p->unk0) >= (u32)p->unk4) {
        OSSendMessage((void*)p->queue, 0x444F4E45, 0);
    }
}



void fn_800074C4(void* arg0){
    Obj_800074C4* p = (Obj_800074C4*)arg0;

    if (p->unk0 & 1) {
        VISetBlack(0);
    }
    else {
        VISetBlack(1);
    }

    VISetNextFrameBuffer(lbl_804A0BC4);
    VIFlush();

    if (p->unk2 != 0) {
        u8 t = p->unk3;
        t ^= 1;
        p->unk3 = t;

        lbl_804A0BC4 = lbl_804A0BCC[p->unk3];
    }
}

// fn_80007544 (size: 0x11C)
void fn_80007660(void){
    VIConfigure(lbl_804A0BD4);
    fn_80007544();
    GXCopyDisp(lbl_804A0BC4, 1);
    GXCopyDisp(lbl_804A0BC4, 1);
    GXFlush();
    GXDrawDone();
    VIFlush();
    VIWaitForRetrace();
    VIWaitForRetrace();
}


void fn_800076B4(void){
    fn_80007270(&lbl_804A0BB8);
}


void fn_800076D8(void){
    GXInvalidateTexAll();
    GXInvalidateVtxCache();
    GXSetScissor(0, 0, lbl_804A0BD4->fbWidth, lbl_804A0BD4->efbHeight);
}
// fn_80007714 (size: 0xD4)

void fn_800077E8(void){
    fn_80007544();

    if (lbl_804A0BB8.unk2 == 1) {
        GXDrawDone();
        GXSetColorUpdate(1);
        GXSetAlphaUpdate(1);
        GXCopyDisp(lbl_804A0BC4, 1);
        GXFlush();

        fn_800074C4(&lbl_804A0BB8);

        OSReceiveMessage((void*)((u8*)&lbl_80398560 + 8), 0, 1);

        lbl_80398560.unk0 = VIGetRetraceCount();
    }
    else {
        fn_80007714();
    }

    {
        void* fb = lbl_804A0BC4;
        JUTDirectPrint* dp = lbl_804A2088;
        changeFrameBuffer__14JUTDirectPrintFPvUsUs(dp, fb, 0x280, 0x1E0);
    }
}
// fn_80007888 (size: 0x74)
// fn_800078FC (size: 0x33C)
// fn_80007C38 (size: 0xF0)
void fn_80007D28(s32 arg0){
    *(u16*)&lbl_804A0BB8 |= arg0;
}


void fn_80007D38(s32 arg0) {
    lbl_80398560.unk4 = arg0;
}
// fn_80007D48 (size: 0x78)
s32 fn_80007DC0(void){
    return (s32)lbl_804A0BC4;
}


s32 fn_80007DC8(void) {
    return lbl_804A0BC8;
}


s32 fn_80007DD0(void) {
    return lbl_80398560.unk4;
}


void fn_80007DE0(s8 arg0) {
    s8 temp_r0;

    lbl_80398560.unk5E = arg0;
    temp_r0 = (s8)(0x1A - arg0);
    lbl_80398560.unk64 = arg0;
    lbl_80398560.unk60 = temp_r0;
    lbl_80398560.unk62 = temp_r0;
}


void fn_80007E00(void) {
    if (VIGetDTVStatus() != 0U) {
        if (((lbl_804A0BF8->unk18 & 0x200U) != 0U) || (OSGetProgressiveMode() != 0U)){
            lbl_804A0BD8 = 1;
            lbl_804A0BDC = 1;
            return;
        }
        OSSetProgressiveMode(0);
        return;
    }
    OSSetProgressiveMode(0);
}


void fn_80007E68(void) {
    if (lbl_804A0BD8 == 1) {
        if (lbl_804A0BF8->unk28 & 0x01000001) {
            lbl_804A0BDC ^= 1;
        }
        if (lbl_804A0BF8->unk28 & 0x02000002) {
            lbl_804A0BDC ^= 1;
        }
        fn_80046D70(lbl_804A0BDC);
    }
}


void fn_80007EDC(void) {
    if ((s8) lbl_804A0BE8 == 0) {
        lbl_804A0BE4 = 0;
        lbl_804A0BE8 = 1;
    }
    if ((s32) lbl_804A0BD8 == 2) {
        if ((s32) lbl_804A0BE0 <= 0) {
            lbl_804A0BD8 = 0;
            return;
        }
        lbl_804A0BE0 -= 1;
        fn_80046D70(lbl_804A0BDC + 2);
    }
}


void fn_80007F4C(void) {
    if (lbl_804A0BD8 == 1) {
        if ((u32)lbl_804A0BDC == OSGetProgressiveMode()) {
            lbl_804A0BE0 = 0;
            lbl_804A0BD8 = 0;
        }
        else {
            lbl_804A0BE0 = 0x5A;
            lbl_804A0BD8 = 2;
        }
        OSSetProgressiveMode((u32)lbl_804A0BDC);
        lbl_804A0BB4 = (u8)OSGetProgressiveMode();
    }
}


void fn_80007FB4(u32* arg0) {
    if (*arg0 == 8U) {
        fn_80007D48(1);
        fn_800391F0(&lbl_803985D4);
        *arg0 = 3U;
    }
}


void fn_80008004(s32* arg0) {
    s32 temp;
    void* p = lbl_803985D4;

    if (fn_80039338(p) == 0) {
        return;
    }

    temp = *arg0;
    if (temp == 2) {
        return;
    }

    if (temp < 2) {
        if (temp >= 1) {
            goto set8;
        }
        goto end;
    }

    /* temp >= 2 */
    if (temp >= 4) {
        goto end;
    }
    goto set0;

    set8:
    *arg0 = 8;
    goto end;

    set0:
    *arg0 = 0;

    end:
    ;
}
// fn_80008080 (size: 0x1EC)
// fn_8000826C (size: 0x10)
void fn_8000827C(s32 arg0) {
    lbl_80398770.unk4 = arg0;
}


void fn_8000828C(s32 arg0) {
    lbl_80398770.unk8 = arg0;
}

