/* autogenerated decompilation stub */
/* source asm: auto_03_80070B38_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_80070B38 (size: 0x8)
// fn_80070B40 (size: 0xB8)
// fn_80070BF8 (size: 0x64)
// fn_80070C5C (size: 0x64)
// fn_80070CC0 (size: 0x8)
// fn_80070CC8 (size: 0x1C)
// fn_80070CE4 (size: 0x8)
// fn_80070CEC (size: 0x74)
// fn_80070D60 (size: 0x60)
