/* autogenerated decompilation stub */
/* source asm: auto_03_8015A624_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_8015A624 (size: 0x110)
// fn_8015A734 (size: 0x84)
// fn_8015A7B8 (size: 0x64)
// fn_8015A81C (size: 0x64)
// fn_8015A880 (size: 0x64)
// fn_8015A8E4 (size: 0x128)
// fn_8015AA0C (size: 0x8)
// fn_8015AA14 (size: 0x1C8)
// fn_8015ABDC (size: 0x30)
// fn_8015AC0C (size: 0x1A8)
// fn_8015ADB4 (size: 0x20)
// fn_8015ADD4 (size: 0x360)
// fn_8015B134 (size: 0x30)
// fn_8015B164 (size: 0x138)
// fn_8015B29C (size: 0x58)
