/* autogenerated decompilation stub */
/* source asm: auto_03_80110364_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_80110364 (size: 0x8)
// fn_8011036C (size: 0x50)
// fn_801103BC (size: 0x6C)
// fn_80110428 (size: 0x64)
// fn_8011048C (size: 0x64)
// fn_801104F0 (size: 0x44)
// fn_80110534 (size: 0x8)
// fn_8011053C (size: 0x8)
// fn_80110544 (size: 0xD8)
// fn_8011061C (size: 0x8)
// fn_80110624 (size: 0x8)
// fn_8011062C (size: 0x8)
// fn_80110634 (size: 0x8)
// fn_8011063C (size: 0x158)
// fn_80110794 (size: 0x8)
// fn_8011079C (size: 0xB4)
// fn_80110850 (size: 0x128)
// fn_80110978 (size: 0x198)
