/* autogenerated decompilation stub */
/* source asm: auto_03_800A0A54_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_800A0A54 (size: 0x8)
// fn_800A0A5C (size: 0x9C)
// fn_800A0AF8 (size: 0x64)
// fn_800A0B5C (size: 0x64)
// fn_800A0BC0 (size: 0x8)
// fn_800A0BC8 (size: 0x8)
// fn_800A0BD0 (size: 0x30)
// fn_800A0C00 (size: 0x28)
// fn_800A0C28 (size: 0xB8)
