/* autogenerated decompilation stub */
/* source asm: auto_03_800F8C50_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_800F8C50 (size: 0x8)
// fn_800F8C58 (size: 0x8)
// fn_800F8C60 (size: 0x8)
// fn_800F8C68 (size: 0x8)
// fn_800F8C70 (size: 0x8C)
// fn_800F8CFC (size: 0x8C)
// fn_800F8D88 (size: 0x18)
// fn_800F8DA0 (size: 0x8)
// fn_800F8DA8 (size: 0x84)
