/* autogenerated decompilation stub */
/* source asm: auto_03_801F5C54_text.s */

/* FUNCTIONS TO DECOMPILE */
// what__Q23std10bad_typeidCFv (size: 0xC)
// what__Q23std8bad_castCFv (size: 0xC)
// ExPPC_LongJump__FP12ThrowContextPvPv (size: 0x74)
// __throw (size: 0xB4)
