/* autogenerated decompilation stub */
/* source asm: auto_03_8017D414_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_8017D414 (size: 0x8)
// fn_8017D41C (size: 0x8C)
// fn_8017D4A8 (size: 0x8C)
// fn_8017D534 (size: 0xA0)
// fn_8017D5D4 (size: 0x10)
// fn_8017D5E4 (size: 0x8)
// fn_8017D5EC (size: 0x70)
// fn_8017D65C (size: 0x8)
// fn_8017D664 (size: 0x88)
// fn_8017D6EC (size: 0x8C)
// fn_8017D778 (size: 0x8C)
// fn_8017D804 (size: 0x8)
// fn_8017D80C (size: 0x238)
// fn_8017DA44 (size: 0x10)
// fn_8017DA54 (size: 0x394)
// fn_8017DDE8 (size: 0xD0)
