/* autogenerated decompilation stub */
/* source asm: auto_03_8017C9B0_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_8017C9B0 (size: 0x8)
// fn_8017C9B8 (size: 0x8C)
// fn_8017CA44 (size: 0x8C)
// fn_8017CAD0 (size: 0xA0)
// fn_8017CB70 (size: 0x10)
// fn_8017CB80 (size: 0x8)
// fn_8017CB88 (size: 0x70)
// fn_8017CBF8 (size: 0x8)
// fn_8017CC00 (size: 0x50)
// fn_8017CC50 (size: 0x90)
// fn_8017CCE0 (size: 0x8C)
// fn_8017CD6C (size: 0x8C)
// fn_8017CDF8 (size: 0x8)
// fn_8017CE00 (size: 0x194)
// fn_8017CF94 (size: 0x10)
// fn_8017CFA4 (size: 0x2D4)
// fn_8017D278 (size: 0xD0)
