/* autogenerated decompilation stub */
/* source asm: auto_03_8015B3F0_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_8015B3F0 (size: 0x8)
// fn_8015B3F8 (size: 0xC4)
// fn_8015B4BC (size: 0x1128)
// fn_8015C5E4 (size: 0x670)
// fn_8015CC54 (size: 0x540)
// fn_8015D194 (size: 0x5B8)
// fn_8015D74C (size: 0x38C)
// fn_8015DAD8 (size: 0x1B4)
// fn_8015DC8C (size: 0xA4)
