/* autogenerated decompilation stub */
/* source asm: auto_03_800F925C_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_800F925C (size: 0x8)
// fn_800F9264 (size: 0x8)
// fn_800F926C (size: 0x8)
// fn_800F9274 (size: 0x58)
// fn_800F92CC (size: 0x94)
// fn_800F9360 (size: 0x8C)
// fn_800F93EC (size: 0x8)
// fn_800F93F4 (size: 0x440)
// fn_800F9834 (size: 0x1DC)
// fn_800F9A10 (size: 0x30)
// fn_800F9A40 (size: 0x2C8)
// fn_800F9D08 (size: 0x14)
// fn_800F9D1C (size: 0x20C)
// fn_800F9F28 (size: 0x14)
// fn_800F9F3C (size: 0x214)
// fn_800FA150 (size: 0x8C)
// fn_800FA1DC (size: 0x16C)
// fn_800FA348 (size: 0xA4)
