/* autogenerated decompilation stub */
/* source asm: auto_03_80022B6C_text.s */
#include "auto_03_80022B6C_text.h"
/* FUNCTIONS TO DECOMPILE */
void fn_80022B6C(void){
    fn_8002E8D0(&lbl_80399C2C, 5, &lbl_802F4F88);
}

// fn_80022BA0 (size: 0x19C)
void fn_80022D3C(void){
    __dla__FPv(*(void**)lbl_80399C2C);
}

// fn_80022D68 (size: 0x250)
// fn_80022FB8 (size: 0x128)
// fn_800230E0 (size: 0x248)
// fn_80023328 (size: 0x20C)
// fn_80023534 (size: 0x2C4)
// fn_800237F8 (size: 0x70)
// fn_80023868 (size: 0x290)
// fn_80023AF8 (size: 0x290)
// fn_80023D88 (size: 0x234)
void fn_80023FBC(void){
    lbl_804A0DB8->unkE4 = lbl_804A27D0;
    fn_8001FC60((void*)lbl_804A0DB8, 2);
    fn_80023D88(lbl_804A0E18, (void*)lbl_804A0DB8, lbl_804A0DB8->unkE4);
    lbl_804A0D2F = 0;
    lbl_80498BD0 = (u8)0xFF;
}
// fn_80024010 (size: 0x84)
void fn_80024094(s32 arg0){
    s32 temp_r3;

    fn_8002BB94(lbl_80399C38);
    temp_r3 = fn_8002BBC4();

    lbl_804A0E1C = 0;
    lbl_804A0E18 = fn_800F1CBC(arg0, temp_r3);

    fn_8001FB18(lbl_80399BE0[0], 1, fn_80024010, fn_80023FBC);
}


void fn_8002410C(s32 arg0){
    s32 temp_r3;

    lbl_80399C20.unk18 = lbl_804A27D0;
    lbl_80399C20.unk1C = lbl_804A27D0;
    lbl_80399C20.unk20 = lbl_804A27D0;

    temp_r3 = fn_8002BBC4();

    lbl_804A0E1C = 0;
    lbl_804A0E18 = fn_800F1CBC(arg0, temp_r3);

    fn_8001FB18(lbl_80399BE0[0], 1, fn_80024010, fn_80023FBC);

}
// fn_800241BC (size: 0x30)
s32 fn_800241EC(void) {
    return lbl_804A0E1C;
}


void fn_800241F4(void){
    lbl_804A0D2F = 0;
    lbl_80498BD0 = 0xFF;

    lbl_804A0DB8->unkE0 = 0;
    lbl_804A0DB8->unkAC = lbl_80498C1C;

    fn_8001FC60(lbl_804A0DB8, 0);
}


void fn_80024240(void) {
    fn_80022238(&lbl_80399C38, 0, lbl_804A2848);
}


void fn_80024270(void) {
    fn_80022238(&lbl_80399C38, 1, lbl_804A2848);
}

// fn_800242A0 (size: 0xF4)
void fn_80024394(void* arg0, s32 arg1){
    Unk_Arg0_3F32* p = (Unk_Arg0_3F32*)arg0;

    lbl_80399C20.unk18 = p->unk0;
    lbl_80399C20.unk1C = p->unk4;
    lbl_80399C20.unk20 = p->unk8;

    if (arg1 == 0) {
        fn_8001FB18(lbl_80399BE0[0], 1, fn_80024240, fn_800241F4);
        return;
    }

    fn_8001FB18(lbl_80399BE0[0], 1, fn_80024270, fn_800241F4);
}


void fn_80024424(void* arg0, s32 arg1, s32 arg2, s32 arg3){
    register Unk_80399C20* r10 = &lbl_80399C20;
    Unk_Arg0_3F32* p = (Unk_Arg0_3F32*)arg0;
    s32 handle;

    r10->unk18 = p->unk0;
    r10->unk1C = p->unk4;
    r10->unk20 = p->unk8;

    lbl_804A0E20 = arg1;

    lbl_804A0E24 = arg2;
    lbl_804A0E28 = arg3;

    handle = lbl_80399BE0[0];

    fn_8001FB18(handle, 1, fn_800242A0, fn_800241F4);
}


void fn_80024494(void){
    fn_8001FBC0(LBL_80399BE0_HANDLE, 1);
}

// fn_800244C4 (size: 0xC38)
// fn_800250FC (size: 0xB4)
void fn_800251B0(s8 arg0){
    if (arg0 == 1) {
        lbl_804A0E30->unk12A4 = lbl_804A2980;
        lbl_804A0E30->unk12A8 = lbl_804A2A04;
        lbl_804A0E30->unk12AC = lbl_804A2A08;
        lbl_804A0E30->unk12BC = -0xAAA;
        lbl_804A0E30->unk12C0 = 0;
        lbl_804A0E30->unk12C4 = 0;
    }
}


s32 fn_80025204(void) {
    return lbl_804A0E34;
}
// fn_8002520C (size: 0x3E4)
f32 fn_800255F0(f32 farg0){
    volatile f32 spC;
    f32 var_f1;
    f64 temp_f2;
    f64 temp_f2_2;
    f64 temp_f2_3;

    var_f1 = farg0;

    if (var_f1 > lbl_804A29FC) {
        temp_f2   = __frsqrte(var_f1);
        temp_f2_2 = lbl_804A2A10 * temp_f2   * (lbl_804A2A18 - ((f64)var_f1 * (temp_f2   * temp_f2)));
        temp_f2_3 = lbl_804A2A10 * temp_f2_2 * (lbl_804A2A18 - ((f64)var_f1 * (temp_f2_2 * temp_f2_2)));

        spC = (f32)((f64)var_f1 * (lbl_804A2A10 * temp_f2_3 * (lbl_804A2A18 - ((f64)var_f1 * (temp_f2_3 * temp_f2_3)))));

        var_f1 = spC;
    }

    return var_f1;
}
// fn_80025660 (size: 0x1A4)
u8 fn_80025804(void) {
    return lbl_804A0E39;
}
// fn_8002580C (size: 0xAC)
// fn_800258B8 (size: 0x168)
// fn_80025A20 (size: 0x1C8)
void fn_80025BE8(void){

    register s32 r31_off;
    register s32 r30_cnt;
    register Unk_Entry_0x24C* r3_e;

    r31_off = 0;
    r30_cnt = 0;

    goto check;

    loop:
    r3_e = (Unk_Entry_0x24C*)((u8*)lbl_804A0E30 + r31_off);

    if ((r3_e->unk3C & 1) && ((u8)r3_e->unk208 == 1)) {
        fn_80025A20();
    }

    r31_off += 0x24C;
    r30_cnt += 1;

    check:
    if (r30_cnt < (s8)lbl_804A0E38) {
        goto loop;
    }
}

// fn_80025C5C (size: 0x80)
void fn_80025CDC(void){
    lbl_804A0DB8->unkB4 = lbl_804A2A34;
    lbl_804A0DB8->unkE0 = 0;
}
// fn_80025CF8 (size: 0x410)
// fn_80026108 (size: 0xFC)
void fn_80026204(void) {}
// fn_80026208 (size: 0xA4)
// fn_800262AC (size: 0x64)
void fn_80026310(void* arg0, u8 arg1){
    Unk_80026310_Arg0* a = (Unk_80026310_Arg0*)arg0;
    s32 temp_r7;
    Unk_EntryBase* p;

    a->unk38 = arg1;
    temp_r7 = a->unk70;

    p = (Unk_EntryBase*)(temp_r7 + ((s32)(s8)a->unk38 << 2));

    fn_8018AFA0((void*)(temp_r7 + 0x94), p->unk6C, 1, 0, (void*)temp_r7);

    a->unk68 = lbl_804A2A4C;
}
// fn_8002636C (size: 0x64)
// fn_800263D0 (size: 0x15C)
// fn_8002652C (size: 0x164)
void fn_80026690(void){
    void* mem;
    register u32 sz2;

    mem = __nwa__FUl(0x58C8U);
    lbl_804A0E48 = (s32)__construct_new_array(mem, (CtorVoid)fn_800266FC, (CtorVoid)0, 0x11C, 0x50);
    sz2 = 0xF788U;
    mem = __nwa__FUl(sz2);
    lbl_804A0E4C = (s32)__construct_new_array(mem, (CtorVoid)fn_8001E448, (CtorVoid)fn_8001E4E8, 0x318, 0x50);
}

void* fn_800266FC(void* arg0){
    Unk_800266FC_Obj* a = (Unk_800266FC_Obj*)arg0;
    f32 v;
    u32 z;

    fn_80026108();

    z = 0;
    a->unk70 = z;

    v = lbl_804A2A4C;
    a->unk44 = v;
    a->unk48 = v;
    a->unk4C = v;

    a->unk5C = z;
    a->unk60 = z;
    a->unk64 = z;

    return arg0;
}
// fn_80026750 (size: 0x13C)
// fn_8002688C (size: 0x114)
// fn_800269A0 (size: 0xE0)
// fn_80026A80 (size: 0xAC)
// fn_80026B2C (size: 0x1B0)
// fn_80026CDC (size: 0x114)
// fn_80026DF0 (size: 0x230)
// fn_80027020 (size: 0x2F8)
// fn_80027318 (size: 0x1A8)
// fn_800274C0 (size: 0x290)
// fn_80027750 (size: 0x1F8)
// fn_80027948 (size: 0x1E0)
// fn_80027B28 (size: 0x274)
// fn_80027D9C (size: 0x598)
// fn_80028334 (size: 0x48)
// fn_8002837C (size: 0x178)
void fn_800284F4(s8 arg0){
    if (arg0 == 1) {
        lbl_804A0E50->unk79C =
        (s32)(lbl_804A0E50->unk79C | 4);
        return;
    }

    lbl_804A0E50->unk79C =
    (s32)(lbl_804A0E50->unk79C & ~4);
}
// fn_80028528 (size: 0x6C)
// fn_80028594 (size: 0x7C)
// fn_80028610 (size: 0xD0)
// fn_800286E0 (size: 0xB4)
// fn_80028794 (size: 0x17C)
// fn_80028910 (size: 0x198)
// fn_80028AA8 (size: 0x1C8)
// fn_80028C70 (size: 0x200)
// fn_80028E70 (size: 0x6C)
void fn_80028EDC(void* arg0, u16 arg1, u16 arg2){
    register Unk_lbl_804A0E5C* r7 = lbl_804A0E5C;
    register Unk_80028EDC_Arg0* a = (Unk_80028EDC_Arg0*)arg0;

    register u16 r4 = arg1;
    register u16 r5 = arg2;

    lbl_803C1C88.unk0 = a->unk0;
    lbl_803C1C88.unk4 = a->unk4;
    lbl_803C1C88.unk8 = a->unk8;

    r7->unk7C = (s32)r5;
    r7->unk74 = (s32)r4;
    r7->unk94 = 2;
}


void fn_80028F18(void* arg0, u16* arg1, u16* arg2){
    Unk_80028F18_Arg0* a = (Unk_80028F18_Arg0*)arg0;

    a->unk0 = lbl_803C1C88.unk0;
    a->unk4 = lbl_803C1C88.unk4;
    a->unk8 = lbl_803C1C88.unk8;

    *arg1 = lbl_804A0E58;
    *arg2 = lbl_804A0E5A;
}


void fn_80028F48(void* arg0){
    Unk_80028F48_Arg0* a = (Unk_80028F48_Arg0*)arg0;
    a->unk3C = a->unk3C & ~1;
}
// fn_80028F58 (size: 0x70)
// fn_80028FC8 (size: 0x70)
// fn_80029038 (size: 0x5C)
// fn_80029094 (size: 0x158)
void* fn_800291EC(void* arg0, s16 arg1){
    if (arg0 != NULL) {
        fn_8001E4E8((void*)((u8*)arg0 + 0x328), (s16)-1);
        fn_8001E4E8((void*)((u8*)arg0 + 0x10),  (s16)-1);

        if (arg1 > 0) {
            __dl__FPv(arg0);
        }
    }
    return arg0;
}


s32 fn_80029250(s32 arg0){
    register s32 r31;

    r31 = *(volatile s32*)&arg0;

    fn_8001E448((void*)(r31 + 0x10));
    fn_8001E448((void*)(r31 + 0x328));

    return r31;
}
// fn_80029290 (size: 0x3F8)
// fn_80029688 (size: 0x130)
// fn_800297B8 (size: 0x64)
s32 fn_8002981C(void){
    if (lbl_804A0E80 == 0) {
        return 0;
    }
    if ((s32)lbl_804A0E80->unk2 == 2) {
        return 1;
    }
    return 0;
}

// fn_8002984C (size: 0x19C)
// fn_800299E8 (size: 0x1CC)
// fn_80029BB4 (size: 0x7C)
// fn_80029C30 (size: 0x160)
void fn_80029D90(void){
    struct {
        u8  pad[0x0C];
        s32 sp14;
    } sp;

    if (lbl_804A0EA0 == 0) {
        fn_80029C30();
        return;
    }

    if (((u32)(*lbl_804A0E84) & 1U) != 0) {
        sp.sp14 = lbl_80498C60;

        fn_80015838((void*)(lbl_80398780 + 0x18C), &sp.sp14);

        fn_8001ED94((void*)lbl_804A0E84, 0xFF);
        fn_8001ED94((void*)((u8*)lbl_804A0E84 + 0x318), 0xFF);
    }
}


void fn_80029E08(void){
    if ((u32)lbl_804A0E84 != 0U) {
        if ((u32)lbl_804A0E80 != 0U) {
            fn_8001F1F8(lbl_804A0E80, 1);
            lbl_804A0E80 = (Unk_lbl_804A0E80*)0;
        }

        __destroy_new_array((void*)lbl_804A0E84, (DtorFn)fn_8001E4E8);
        __destroy_new_array(lbl_804A0EA4, fn_800291EC);

        lbl_804A0E84 = (void*)0;
    }
}
// fn_80029E74 (size: 0x104)
// fn_80029F78 (size: 0x124)
void fn_8002A09C(f32 farg0, f32 farg1, f32 farg2){
    lbl_803C1C98.unk418 = farg0;
    lbl_803C1C98.unk41C = farg1;
    lbl_803C1C98.unk420 = farg2;
}
// fn_8002A0B4 (size: 0x100)
// fn_8002A1B4 (size: 0x1AC)
// fn_8002A360 (size: 0x358)
// fn_8002A6B8 (size: 0x1E8)
// fn_8002A8A0 (size: 0x1E8)
// fn_8002AA88 (size: 0x20C)
// fn_8002AC94 (size: 0xC0)
// fn_8002AD54 (size: 0x1D0)
// fn_8002AF24 (size: 0xA4)
// fn_8002AFC8 (size: 0x104)
// fn_8002B0CC (size: 0x2C)
s32 fn_8002B0F8(s32 arg0, s32 arg1) {
    s32 temp_r0;

    temp_r0 = lbl_804A1294 + (lbl_804A1290 * 0x3C);
    if ((temp_r0 >= arg0) && (temp_r0 < arg1)) {
        return 1;
    }
    if (temp_r0 >= arg1) {
        return 2;
    }
    return 0;
}


void fn_8002B138(void* arg0){
    Unk_8002B138_Arg0* p = (Unk_8002B138_Arg0*)arg0;

    p->unk0  = 0;
    p->unk2C = 0;
}

// fn_8002B148 (size: 0x170)
void fn_8002B2B8(s32 unused, s32 arg1){
    s32* temp_r3;
    (void)unused;

    temp_r3 = fn_80006A3C(arg1);
    *temp_r3 |= 0x10;
}

// fn_8002B2E8 (size: 0xE8)
// fn_8002B3D0 (size: 0x298)
// fn_8002B668 (size: 0x170)
// fn_8002B7D8 (size: 0x60)
// fn_8002B838 (size: 0xDC)
// fn_8002B914 (size: 0x244)
void fn_8002BB58(void) {}
s32 fn_8002BB5C(void) {
    return lbl_804A0EF0->unk3C;
}


void fn_8002BB68(void) {
    *(s32*)lbl_804A0EF0 |= 2;
}


s16 fn_8002BB7C(void) {
    return lbl_804A0EF0->unk38;
}


s32 fn_8002BB88(void) {
    return lbl_804A0EF0->unk54;
}

// fn_8002BB94 (size: 0x30)
s32 fn_8002BBC4(void) {
    return lbl_804A0EF0->unk2C;
}
// fn_8002BBD0 (size: 0x64)
// fn_8002BC34 (size: 0x178)
// fn_8002BDAC (size: 0xB8)
// fn_8002BE64 (size: 0x114)
// fn_8002BF78 (size: 0x1FC)
// fn_8002C174 (size: 0x100)
// fn_8002C274 (size: 0x108)
// fn_8002C37C (size: 0x11C)
// fn_8002C498 (size: 0x12C)
s32 fn_8002C5C4(void) {
    return 1;
}


s32 fn_8002C5CC(void* arg0) {
    Unk_8002C5CC_Arg0* a = (Unk_8002C5CC_Arg0*)arg0;
    s32 var_r31;
    u32 tmp;
    u8  arg;

    var_r31 = 0;

    tmp = a->unk40;
    tmp = tmp >> 24;
    arg = (u8)tmp;

    if (fn_8001CA78(arg, 0) == 0) {
        var_r31 = 1;
    }
    return var_r31;
}
// fn_8002C618 (size: 0xEC)
s32 fn_8002C704(void) {
    return 0;
}


void fn_8002C70C(void) {
    Unk_800E7E7C_Ret* temp_r3;

    lbl_804A0C08 = 0;
    fn_8002418C();
    fn_800F2458();
    fn_80043824();
    fn_80065120();

    if (fn_800660F0() == 0U) {
        temp_r3 = (Unk_800E7E7C_Ret*)fn_800E7E7C(0);
        temp_r3->unk40 &= 0xFFFFF3FFu;
    }

    fn_80065398(0x5E);
}


void fn_8002C768(void) {
    fn_8002BBC4();
}


void fn_8002C788(void) {
    fn_8002BB5C();
}


void fn_8002C7A8(void) { }
void fn_8002C7AC(void) { }


void fn_8002C7B0(void) {
    fn_8002BB5C();
}


void fn_8002C7D0(void) { }


void fn_8002C7D4(void) {
    fn_8002BBC4();
    fn_80120294();
}


void fn_8002C7F8(void) {
    fn_8002BB5C();
    fn_80120CB0();
}

void fn_8002C81C(void) {
    fn_8012032C();
}


void fn_8002C83C(void) { }

void fn_8002C840(void) {
    fn_8002BB5C();
}

void fn_8002C860(void) {}

void fn_8002C864(void) {}

void fn_8002C868(void) {}

void fn_8002C86C(void) {}


void fn_8002C870(void){
    Unk_804A1240* temp_r3;
    u8 pad[8];
    (void)pad;

    temp_r3 = (Unk_804A1240*)__nw__FUl(0x30U);
    if (temp_r3 != NULL) {
        fn_8005F57C(temp_r3);
    }

    lbl_804A1240 = temp_r3;
    *(s32*)temp_r3 = 2;
    fn_8005F868();
}


void fn_8002C8BC(void){
    u8 sp8[0x30];
    u32 p;

    fn_80028528(sp8);

    p = (u32)lbl_804A1240;
    p = *(u32*)(p + 0x24);

    if (p != 0) {
        fn_80058A8C((void*)p, sp8);
    }
}


void fn_8002C8F8(void){
    fn_8005F5D0(lbl_804A1240, 1);
    lbl_804A1240 = NULL;
    fn_8005F8B0();
}


void fn_8002C92C(void) {
    Unk_804A1240* p;
    Unk_804A1240* q;

    u8 pad[8];
    #pragma unused(pad)

    p = (Unk_804A1240*)__nw__FUl(0x30U);
    if (p != NULL) {
        fn_8005F57C(p);
    }
    lbl_804A1240 = p;
    *(s32*)p = 5;

    q = (Unk_804A1240*)__nw__FUl(0x30U);
    if (q != NULL) {
        fn_8005F57C(q);
    }
    lbl_804A1244 = q;
    *(s32*)q = 5;

    fn_8005F8E0();
}
// fn_8002C99C (size: 0xF8)
void fn_8002CA94(void) {
    fn_8005FEE8();
    fn_8005F5D0(lbl_804A1240, 1);
    lbl_804A1240 = 0;
    fn_8005F5D0(lbl_804A1244, 1);
    lbl_804A1244 = 0;
}


void fn_8002CAE0(void) {}
void fn_8002CAE4(void) {}
void fn_8002CAE8(void) {}
void fn_8002CAEC(void) {}
void fn_8002CAF0(void) {}
void fn_8002CAF4(void) {}
void fn_8002CAF8(void) {}
void fn_8002CAFC(void) {}
void fn_8002CB00(void) {}
void fn_8002CB04(void) {}
void fn_8002CB08(void) {}
void fn_8002CB0C(void) {}
void fn_8002CB10(void) {}
void fn_8002CB14(void) {}
void fn_8002CB18(void) {}
void fn_8002CB1C(void) {}
void fn_8002CB20(void) {}
void fn_8002CB24(void) {}
void fn_8002CB28(void) {}
void fn_8002CB2C(void) {}
void fn_8002CB30(void) {}
void fn_8002CB34(void) {}
void fn_8002CB38(void) {}
void fn_8002CB3C(void) {}
void fn_8002CB40(void) {}
void fn_8002CB44(void) {}
void fn_8002CB48(void) {}
void fn_8002CB4C(void) {}
void fn_8002CB50(void) {}
void fn_8002CB54(void) {}
void fn_8002CB58(void) {}
void fn_8002CB5C(void) {}
void fn_8002CB60(void) {}
void fn_8002CB64(void) {}
void fn_8002CB68(void) {}
void fn_8002CB6C(void) {}
void fn_8002CB70(void) {}
void fn_8002CB74(void) {}
void fn_8002CB78(void) {}
void fn_8002CB7C(void) {}
void fn_8002CB80(void) {}
void fn_8002CB84(void) {}
void fn_8002CB88(void) {}
void fn_8002CB8C(void) {}
void fn_8002CB90(void) {}
void fn_8002CB94(void) {}
void fn_8002CB98(void) {}
void fn_8002CB9C(void) {}
void fn_8002CBA0(void) {}
void fn_8002CBA4(void) {}
void fn_8002CBA8(void) {}
void fn_8002CBAC(void) {}
void fn_8002CBB0(void) {}
void fn_8002CBB4(void) {}

void fn_8002CBB8(void) {
    fn_8003726C();
}

void fn_8002CBD8(void) {}
void fn_8002CBDC(void) {}
void fn_8002CBE0(void) {}
void fn_8002CBE4(void) {}
void fn_8002CBE8(void) {}
void fn_8002CBEC(void) {}
void fn_8002CBF0(void) {}
void fn_8002CBF4(void) {}
void fn_8002CBF8(void) {}
void fn_8002CBFC(void) {}
void fn_8002CC00(void) {}
void fn_8002CC04(void) {}
void fn_8002CC08(void) {}
void fn_8002CC0C(void) {}
void fn_8002CC10(void) {}
void fn_8002CC14(void) {}
void fn_8002CC18(void) {}
void fn_8002CC1C(void) {}
void fn_8002CC20(void) {}
void fn_8002CC24(void) {}
void fn_8002CC28(void) {}
void fn_8002CC2C(void) {}
void fn_8002CC30(void) {}
void fn_8002CC34(void) {}
void fn_8002CC38(void) {}
void fn_8002CC3C(void) {}
void fn_8002CC40(void) {}
void fn_8002CC44(void) {}
void fn_8002CC48(void) {}
void fn_8002CC4C(void) {}


void fn_8002CC50(void) {
    fn_80037404();
}


void fn_8002CC70(void) {}
void fn_8002CC74(void) {}
void fn_8002CC78(void) {}
void fn_8002CC7C(void) {}
void fn_8002CC80(void) {}
void fn_8002CC84(void) {}
void fn_8002CC88(void) {}
void fn_8002CC8C(void) {}
void fn_8002CC90(void) {}
void fn_8002CC94(void) {}
void fn_8002CC98(void) {}
void fn_8002CC9C(void) {}
void fn_8002CCA0(void) {}
void fn_8002CCA4(void) {}
void fn_8002CCA8(void) {}
void fn_8002CCAC(void) {}
void fn_8002CCB0(void) {}
void fn_8002CCB4(void) {}
void fn_8002CCB8(void) {}
void fn_8002CCBC(void) {}
void fn_8002CCC0(void) {}
void fn_8002CCC4(void) {}
void fn_8002CCC8(void) {}
void fn_8002CCCC(void) {}
void fn_8002CCD0(void) {}
void fn_8002CCD4(void) {}
void fn_8002CCD8(void) {}
void fn_8002CCDC(void) {}
void fn_8002CCE0(void) {}
void fn_8002CCE4(void) {}
void fn_8002CCE8(void) {}
void fn_8002CCEC(void) {}
void fn_8002CCF0(void) {}
void fn_8002CCF4(void) {}
void fn_8002CCF8(void) {}
void fn_8002CCFC(void) {}
void fn_8002CD00(void) {}
void fn_8002CD04(void) {}
void fn_8002CD08(void) {}
void fn_8002CD0C(void) {}
void fn_8002CD10(void) {}
void fn_8002CD14(void) {}
void fn_8002CD18(void) {}
void fn_8002CD1C(void) {}
void fn_8002CD20(void) {}
void fn_8002CD24(void) {}
void fn_8002CD28(void) {}
void fn_8002CD2C(void) {}
void fn_8002CD30(void) {}


void fn_8002CD34(void) {
    fn_8002BBC4();
    fn_801202E0();
}


void fn_8002CD58(void) {
    fn_8002BB5C();
    fn_80120CDC();
}


void fn_8002CD7C(void) {
    fn_8012032C();
}
void fn_8002CD9C(void) {}
void fn_8002CDA0(void) {}
void fn_8002CDA4(void) {}
void fn_8002CDA8(void) {}
void fn_8002CDAC(void) {}
void fn_8002CDB0(void) {}
void fn_8002CDB4(void) {}
void fn_8002CDB8(void) {}
void fn_8002CDBC(void) {}
void fn_8002CDC0(void) {}
void fn_8002CDC4(void) {}
void fn_8002CDC8(void) {}
void fn_8002CDCC(void) {}
void fn_8002CDD0(void) {}
void fn_8002CDD4(void) {}
void fn_8002CDD8(void) {}
void fn_8002CDDC(void) {}
void fn_8002CDE0(void) {}
void fn_8002CDE4(void) {}
void fn_8002CDE8(void) {}
void fn_8002CDEC(void) {}
void fn_8002CDF0(void) {}
void fn_8002CDF4(void) {}
void fn_8002CDF8(void) {}
void fn_8002CDFC(void) {}
void fn_8002CE00(void) {}
void fn_8002CE04(void) {}
void fn_8002CE08(void) {}
void fn_8002CE0C(void) {}
void fn_8002CE10(void) {}
void fn_8002CE14(void) {}
void fn_8002CE18(void) {}
void fn_8002CE1C(void) {}
void fn_8002CE20(void) {}
void fn_8002CE24(void) {}


void fn_8002CE28(void) {
    void* tmp;

    fn_800E7F08(&lbl_80498C68);
    tmp = fn_80096CAC();
    fn_800C0A28(tmp, 1);
}


void fn_8002CE58(void) {}
void fn_8002CE5C(void) {}
void fn_8002CE60(void) {}
void fn_8002CE64(void) {}
void fn_8002CE68(void) {}
void fn_8002CE6C(void) {}
void fn_8002CE70(void) {}
void fn_8002CE74(void) {}
void fn_8002CE78(void) {}
void fn_8002CE7C(void) {}
void fn_8002CE80(void) {}


void fn_8002CE84(void) {
    fn_8003738C();
}


void fn_8002CEA4(void) {}
void fn_8002CEA8(void) {}
void fn_8002CEAC(void) {}
void fn_8002CEB0(void) {}
void fn_8002CEB4(void) {}
void fn_8002CEB8(void) {}
void fn_8002CEBC(void) {}
void fn_8002CEC0(void) {}
void fn_8002CEC4(void) {}
void fn_8002CEC8(void) {}
void fn_8002CECC(void) {}
void fn_8002CED0(void) {}
void fn_8002CED4(void) {}
void fn_8002CED8(void) {}
void fn_8002CEDC(void) {}
void fn_8002CEE0(void) {}
void fn_8002CEE4(void) {}
void fn_8002CEE8(void) {}
void fn_8002CEEC(void) {}
void fn_8002CEF0(void) {}


void fn_8002CEF4(void) {
    void* tmp;

    fn_800E7F08(&lbl_802F54B8);
    tmp = fn_80096CAC();
    fn_800C0A28(tmp, 0xC);
}


void fn_8002CF28(void) {}
void fn_8002CF2C(void) {}
void fn_8002CF30(void) {}
void fn_8002CF34(void) {}
void fn_8002CF38(void) {}
void fn_8002CF3C(void) {}
void fn_8002CF40(void) {}
void fn_8002CF44(void) {}
void fn_8002CF48(void) {}
void fn_8002CF4C(void) {}
void fn_8002CF50(void) {}
void fn_8002CF54(void) {}
void fn_8002CF58(void) {}
void fn_8002CF5C(void) {}
void fn_8002CF60(void) {}
void fn_8002CF64(void) {}
void fn_8002CF68(void) {}
void fn_8002CF6C(void) {}
void fn_8002CF70(void) {}
void fn_8002CF74(void) {}
void fn_8002CF78(void) {}
void fn_8002CF7C(void) {}
void fn_8002CF80(void) {}
void fn_8002CF84(void) {}
void fn_8002CF88(void) {}
void fn_8002CF8C(void) {}
void fn_8002CF90(void) {}
void fn_8002CF94(void) {}
void fn_8002CF98(void) {}
void fn_8002CF9C(void) {}
void fn_8002CFA0(void) {}
void fn_8002CFA4(void) {}
void fn_8002CFA8(void) {}
void fn_8002CFAC(void) {}
void fn_8002CFB0(void) {}
void fn_8002CFB4(void) {}
void fn_8002CFB8(void) {}
void fn_8002CFBC(void) {}
void fn_8002CFC0(void) {}
void fn_8002CFC4(void) {}
void fn_8002CFC8(void) {}
void fn_8002CFCC(void) {}
void fn_8002CFD0(void) {}
void fn_8002CFD4(void) {}
void fn_8002CFD8(void) {}
void fn_8002CFDC(void) {}
void fn_8002CFE0(void) {}
void fn_8002CFE4(void) {}
void fn_8002CFE8(void) {}
void fn_8002CFEC(void) {}
void fn_8002CFF0(void) {}
void fn_8002CFF4(void) {}
void fn_8002CFF8(void) {}
void fn_8002CFFC(void) {}
void fn_8002D000(void) {}
void fn_8002D004(void) {}
void fn_8002D008(void) {}
void fn_8002D00C(void) {}
void fn_8002D010(void) {}
void fn_8002D014(void) {}
void fn_8002D018(void) {}
void fn_8002D01C(void) {}
void fn_8002D020(void) {}
void fn_8002D024(void) {}
void fn_8002D028(void) {}
void fn_8002D02C(void) {}
void fn_8002D030(void) {}
void fn_8002D034(void) {}
void fn_8002D038(void) {}
void fn_8002D03C(void) {}
void fn_8002D040(void) {}
void fn_8002D044(void) {}
void fn_8002D048(void) {}
void fn_8002D04C(void) {}
void fn_8002D050(void) {}
void fn_8002D054(void) {}
void fn_8002D058(void) {}
void fn_8002D05C(void) {}
void fn_8002D060(void) {}
void fn_8002D064(void) {}
void fn_8002D068(void) {}
void fn_8002D06C(void) {}
void fn_8002D070(void) {}
void fn_8002D074(void) {}
void fn_8002D078(void) {}
void fn_8002D07C(void) {}
void fn_8002D080(void) {}
void fn_8002D084(void) {}
void fn_8002D088(void) {}
void fn_8002D08C(void) {}
void fn_8002D090(void) {}
void fn_8002D094(void) {}
void fn_8002D098(void) {}
void fn_8002D09C(void) {}
void fn_8002D0A0(void) {}
void fn_8002D0A4(void) {}
void fn_8002D0A8(void) {}
void fn_8002D0AC(void) {}
void fn_8002D0B0(void) {}

// fn_8002D0B4 (size: 0x2F8)
// fn_8002D3AC (size: 0x6C)
// fn_8002D418 (size: 0x6C)
// fn_8002D484 (size: 0x6C)
// fn_8002D4F0 (size: 0x128)
// fn_8002D618 (size: 0x26C)
// fn_8002D884 (size: 0x208)
// fn_8002DA8C (size: 0x258)
// fn_8002DCE4 (size: 0x150)
// fn_8002DE34 (size: 0x58)
// fn_8002DE8C (size: 0x7A0)
void fn_8002E62C(void) {
    fn_8002DA8C(&lbl_803C236C);
}
// fn_8002E654 (size: 0x1E8)
// fn_8002E83C (size: 0x74)
