/* autogenerated decompilation stub */
/* source asm: auto_03_800DA19C_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_800DA19C (size: 0x64)
// fn_800DA200 (size: 0x64)
// fn_800DA264 (size: 0x8)
// fn_800DA26C (size: 0x28)
// fn_800DA294 (size: 0x78)
// fn_800DA30C (size: 0xC8)
// fn_800DA3D4 (size: 0x34)
// fn_800DA408 (size: 0x48)
// fn_800DA450 (size: 0x68)
// fn_800DA4B8 (size: 0xDC)
// fn_800DA594 (size: 0x58)
// fn_800DA5EC (size: 0x198)
// fn_800DA784 (size: 0x2C)
// fn_800DA7B0 (size: 0x2C)
