/* autogenerated decompilation stub */
/* source asm: auto_03_801CCE8C_text.s */

/* FUNCTIONS TO DECOMPILE */
// create__13JKRAramStreamFl (size: 0x6C)
// __ct__13JKRAramStreamFl (size: 0x58)
// __dt__13JKRAramStreamFv (size: 0x64)
// run__13JKRAramStreamFv (size: 0x68)
// readFromAram__13JKRAramStreamFv (size: 0x8)
// writeToAram__13JKRAramStreamFP20JKRAramStreamCommand (size: 0x1C0)
// setTransBuffer__13JKRAramStreamFPUcUlP7JKRHeap (size: 0x54)
// __ct__20JKRAramStreamCommandFv (size: 0x5C)
// __ct__13JKRFileLoaderFv (size: 0x60)
// __dt__13JKRFileLoaderFv (size: 0x8C)
// unmount__13JKRFileLoaderFv (size: 0x50)
// getGlbResource__13JKRFileLoaderFPCc (size: 0x58)
// getGlbResource__13JKRFileLoaderFPCcP13JKRFileLoader (size: 0x98)
// removeResource__13JKRFileLoaderFPvP13JKRFileLoader (size: 0x90)
// findVolume__13JKRFileLoaderFPPCc (size: 0x8C)
// fetchVolumeName__13JKRFileLoaderFPclPCc (size: 0xC8)
