/* autogenerated decompilation stub */
/* source asm: auto_03_80156EA4_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_80156EA4 (size: 0x110)
// fn_80156FB4 (size: 0x64)
// fn_80157018 (size: 0x4C)
// fn_80157064 (size: 0x74)
// fn_801570D8 (size: 0x7C)
// fn_80157154 (size: 0x7C)
// fn_801571D0 (size: 0x12C)
// fn_801572FC (size: 0x118)
// fn_80157414 (size: 0xBC)
// fn_801574D0 (size: 0x194)
