/* autogenerated decompilation stub */
/* source asm: auto_03_8006AAAC_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_8006AAAC (size: 0x8)
// fn_8006AAB4 (size: 0x8)
// fn_8006AABC (size: 0x8)
// fn_8006AAC4 (size: 0x8)
// fn_8006AACC (size: 0x64)
// fn_8006AB30 (size: 0x64)
// fn_8006AB94 (size: 0x10)
// fn_8006ABA4 (size: 0x8)
// fn_8006ABAC (size: 0x44)
// fn_8006ABF0 (size: 0x54)
// fn_8006AC44 (size: 0xD0)
// fn_8006AD14 (size: 0xC4)
// fn_8006ADD8 (size: 0x8)
