/* autogenerated decompilation stub */
/* source asm: auto_03_80108C7C_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_80108C7C (size: 0x8)
// fn_80108C84 (size: 0x8)
// fn_80108C8C (size: 0x64)
// fn_80108CF0 (size: 0x64)
// fn_80108D54 (size: 0x54)
// fn_80108DA8 (size: 0x28)
// fn_80108DD0 (size: 0xFC)
// fn_80108ECC (size: 0xE0)
// fn_80108FAC (size: 0x38)
// fn_80108FE4 (size: 0x34)
// fn_80109018 (size: 0x3C)
// fn_80109054 (size: 0x6C)
