/* autogenerated decompilation stub */
/* source asm: auto_03_80043E40_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_80043E40 (size: 0x30)
// fn_80043E70 (size: 0x54)
// fn_80043EC4 (size: 0x198)
// fn_8004405C (size: 0x610)
// fn_8004466C (size: 0x160)
// fn_800447CC (size: 0x74)
