/* autogenerated decompilation stub */
/* source asm: auto_03_80045F78_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_80045F78 (size: 0x30)
// fn_80045FA8 (size: 0x54)
// fn_80045FFC (size: 0x48)
// fn_80046044 (size: 0x4)
// fn_80046048 (size: 0x4)
// fn_8004604C (size: 0x4)
// fn_80046050 (size: 0x138)
// fn_80046188 (size: 0x40)
// fn_800461C8 (size: 0x4)
// fn_800461CC (size: 0x4)
// fn_800461D0 (size: 0x40)
