/* autogenerated decompilation stub */
/* source asm: auto_03_8010E52C_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_8010E52C (size: 0x8)
// fn_8010E534 (size: 0x7C)
// fn_8010E5B0 (size: 0x128)
// fn_8010E6D8 (size: 0x48)
// fn_8010E720 (size: 0x74)
// fn_8010E794 (size: 0x190)
// fn_8010E924 (size: 0x3C)
// fn_8010E960 (size: 0x3EC)
// fn_8010ED4C (size: 0x78)
// fn_8010EDC4 (size: 0x80)
// fn_8010EE44 (size: 0x8)
// fn_8010EE4C (size: 0x68)
// fn_8010EEB4 (size: 0x1C)
// fn_8010EED0 (size: 0x68)
// fn_8010EF38 (size: 0x148)
// fn_8010F080 (size: 0xAC)
// fn_8010F12C (size: 0xC4)
// fn_8010F1F0 (size: 0x78)
