/* autogenerated decompilation stub */
/* source asm: auto_03_80177D5C_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_80177D5C (size: 0x40)
// fn_80177D9C (size: 0xB8)
// fn_80177E54 (size: 0x4)
// fn_80177E58 (size: 0x78)
// fn_80177ED0 (size: 0x78)
// fn_80177F48 (size: 0x78)
// fn_80177FC0 (size: 0x78)
// fn_80178038 (size: 0x80)
// fn_801780B8 (size: 0x68)
// fn_80178120 (size: 0x3E4)
// fn_80178504 (size: 0x4C)
// fn_80178550 (size: 0xD0)
// fn_80178620 (size: 0x12C)
// fn_8017874C (size: 0x88)
// fn_801787D4 (size: 0x150)
// fn_80178924 (size: 0x8)
// fn_8017892C (size: 0x64)
// fn_80178990 (size: 0x48)
// fn_801789D8 (size: 0x10)
// fn_801789E8 (size: 0x4)
