/* autogenerated decompilation stub */
/* source asm: auto_03_8003F200_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_8003F200 (size: 0x18C)
// fn_8003F38C (size: 0xB8)
// fn_8003F444 (size: 0x154)
// fn_8003F598 (size: 0x74)
// fn_8003F60C (size: 0x7C)
// fn_8003F688 (size: 0x284)
// fn_8003F90C (size: 0x81C)
