/* autogenerated decompilation stub */
/* source asm: auto_03_8010FC30_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_8010FC30 (size: 0x8)
// fn_8010FC38 (size: 0x44)
// fn_8010FC7C (size: 0x6C)
// fn_8010FCE8 (size: 0x64)
// fn_8010FD4C (size: 0x64)
// fn_8010FDB0 (size: 0x4)
// fn_8010FDB4 (size: 0x28)
// fn_8010FDDC (size: 0x8)
// fn_8010FDE4 (size: 0x28)
// fn_8010FE0C (size: 0x8)
// fn_8010FE14 (size: 0x8)
// fn_8010FE1C (size: 0x8)
// fn_8010FE24 (size: 0x8)
// fn_8010FE2C (size: 0x38)
// fn_8010FE64 (size: 0x80)
// fn_8010FEE4 (size: 0x384)
