/* autogenerated decompilation stub */
/* source asm: auto_03_80159B44_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_80159B44 (size: 0x8)
// fn_80159B4C (size: 0x8)
// fn_80159B54 (size: 0x8)
// fn_80159B5C (size: 0x3C)
// fn_80159B98 (size: 0x64)
// fn_80159BFC (size: 0x64)
// fn_80159C60 (size: 0x64)
// fn_80159CC4 (size: 0x110)
// fn_80159DD4 (size: 0x28)
// fn_80159DFC (size: 0x8)
// fn_80159E04 (size: 0x38)
// fn_80159E3C (size: 0xA0)
// fn_80159EDC (size: 0x180)
// fn_8015A05C (size: 0x7C)
