/* autogenerated decompilation stub */
/* source asm: auto_03_800448A0_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_800448A0 (size: 0x30)
// fn_800448D0 (size: 0x54)
// fn_80044924 (size: 0x1AC)
// fn_80044AD0 (size: 0x768)
// fn_80045238 (size: 0x30C)
// fn_80045544 (size: 0xA8)
// fn_800455EC (size: 0x94)
// fn_80045680 (size: 0x30)
