/* autogenerated decompilation stub */
/* source asm: auto_03_8014DB14_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_8014DB14 (size: 0x8)
// fn_8014DB1C (size: 0x8)
// fn_8014DB24 (size: 0x8)
// fn_8014DB2C (size: 0x8C)
// fn_8014DBB8 (size: 0x4C)
// fn_8014DC04 (size: 0x64)
// fn_8014DC68 (size: 0xA8)
// fn_8014DD10 (size: 0x64)
// fn_8014DD74 (size: 0xAC)
// fn_8014DE20 (size: 0x80)
// fn_8014DEA0 (size: 0x30)
// fn_8014DED0 (size: 0x74)
// fn_8014DF44 (size: 0x8)
// fn_8014DF4C (size: 0x98)
// fn_8014DFE4 (size: 0x30)
// fn_8014E014 (size: 0x44)
// fn_8014E058 (size: 0xF0)
// fn_8014E148 (size: 0x104)
// fn_8014E24C (size: 0xCC)
