/* autogenerated decompilation stub */
/* source asm: auto_03_800C373C_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_800C373C (size: 0x8)
// fn_800C3744 (size: 0x30)
// fn_800C3774 (size: 0x10)
// fn_800C3784 (size: 0x4C)
// fn_800C37D0 (size: 0x40)
// fn_800C3810 (size: 0x30)
// fn_800C3840 (size: 0x54)
// fn_800C3894 (size: 0x64)
// fn_800C38F8 (size: 0x64)
// fn_800C395C (size: 0x8)
// fn_800C3964 (size: 0x3B4)
// fn_800C3D18 (size: 0x8)
// fn_800C3D20 (size: 0x1EC)
// fn_800C3F0C (size: 0x8)
// fn_800C3F14 (size: 0x180)
// fn_800C4094 (size: 0x64)
