/* autogenerated decompilation stub */
/* source asm: auto_03_80123FFC_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_80123FFC (size: 0xAC)
// fn_801240A8 (size: 0xB8)
// fn_80124160 (size: 0x90)
// fn_801241F0 (size: 0x64)
// fn_80124254 (size: 0x38)
// fn_8012428C (size: 0x8)
// fn_80124294 (size: 0x12C)
// fn_801243C0 (size: 0x34)
// fn_801243F4 (size: 0x8)
