/* autogenerated decompilation stub */
/* source asm: auto_03_800DD284_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_800DD284 (size: 0x8)
// fn_800DD28C (size: 0x74)
// fn_800DD300 (size: 0x64)
// fn_800DD364 (size: 0x64)
// fn_800DD3C8 (size: 0x8)
// fn_800DD3D0 (size: 0x28)
// fn_800DD3F8 (size: 0x74)
// fn_800DD46C (size: 0xE0)
// fn_800DD54C (size: 0x30)
// fn_800DD57C (size: 0x118)
// fn_800DD694 (size: 0x70)
