/* autogenerated decompilation stub */
/* source asm: auto_03_8015A174_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_8015A174 (size: 0x3C)
// fn_8015A1B0 (size: 0x64)
// fn_8015A214 (size: 0x8C)
// fn_8015A2A0 (size: 0x8C)
// fn_8015A32C (size: 0x13C)
// fn_8015A468 (size: 0x28)
// fn_8015A490 (size: 0x80)
