/* autogenerated decompilation stub */
/* source asm: auto_03_80108644_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_80108644 (size: 0x44)
// fn_80108688 (size: 0x8C)
// fn_80108714 (size: 0x8C)
// fn_801087A0 (size: 0x8)
// fn_801087A8 (size: 0x110)
// fn_801088B8 (size: 0x8)
// fn_801088C0 (size: 0x84)
// fn_80108944 (size: 0x24)
// fn_80108968 (size: 0x3C)
// fn_801089A4 (size: 0x20)
// fn_801089C4 (size: 0xE0)
// fn_80108AA4 (size: 0xE8)
// fn_80108B8C (size: 0x84)
