/* autogenerated decompilation stub */
/* source asm: auto_03_801F6FC8_text.s */

/* FUNCTIONS TO DECOMPILE */
// ExPPC_FindExceptionFragment__FPcP12FragmentInfo (size: 0x98)
// __unregister_fragment (size: 0x34)
// __register_fragment (size: 0x3C)
// what__Q23std13bad_exceptionCFv (size: 0xC)
// __cvt_fp2unsigned (size: 0x5C)
// __save_fpr (size: 0x4C)
// __restore_fpr (size: 0x4C)
// __save_gpr (size: 0x4C)
// __restore_gpr (size: 0x4C)
// __div2u (size: 0xEC)
// __div2i (size: 0x138)
// __mod2u (size: 0xE4)
// __mod2i (size: 0x10C)
// __shl2i (size: 0x24)
// __shr2u (size: 0x24)
// __shr2i (size: 0x28)
// GetR2__Fv_801F76EC (size: 0x8)
