/* autogenerated decompilation stub */
/* source asm: auto_03_8017B720_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_8017B720 (size: 0x8C)
// fn_8017B7AC (size: 0x8C)
// fn_8017B838 (size: 0xA0)
// fn_8017B8D8 (size: 0x10)
// fn_8017B8E8 (size: 0x8)
// fn_8017B8F0 (size: 0x74)
// fn_8017B964 (size: 0x8)
// fn_8017B96C (size: 0x5C)
// fn_8017B9C8 (size: 0xBC)
// fn_8017BA84 (size: 0x8C)
// fn_8017BB10 (size: 0x8C)
// fn_8017BB9C (size: 0x8)
// fn_8017BBA4 (size: 0x294)
// fn_8017BE38 (size: 0x14)
// fn_8017BE4C (size: 0x524)
// fn_8017C370 (size: 0x60)
// fn_8017C3D0 (size: 0x84)
// fn_8017C454 (size: 0x1E0)
// fn_8017C634 (size: 0x1E0)
// fn_8017C814 (size: 0xD0)
