/* autogenerated decompilation stub */
/* source asm: auto_03_8004CF54_text.s */

/* FUNCTIONS TO DECOMPILE */
// fn_8004CF54 (size: 0xC)
// fn_8004CF60 (size: 0x410)
// fn_8004D370 (size: 0x5C)
// fn_8004D3CC (size: 0xDC8)
// fn_8004E194 (size: 0x134)
// fn_8004E2C8 (size: 0xA28)
// fn_8004ECF0 (size: 0x96C)
// fn_8004F65C (size: 0x338)
// fn_8004F994 (size: 0x428)
// fn_8004FDBC (size: 0xDC)
// fn_8004FE98 (size: 0xDC)
// fn_8004FF74 (size: 0x24)
// fn_8004FF98 (size: 0x24)
// fn_8004FFBC (size: 0x40)
// fn_8004FFFC (size: 0x30)
// fn_8005002C (size: 0x54)
// fn_80050080 (size: 0x8C)
// fn_8005010C (size: 0xFC)
// fn_80050208 (size: 0x2E0)
// fn_800504E8 (size: 0x28)
